### ISSUE TITLE
Add Empty Spring Boot Sample

### ISSUE THREAD

**Issue by jzheaux** [spring-projects-experimental/spring-authorization-server#1]
The security team likes to start coding by placing all the code into a sample. We later extract it out into more framework-like code.

We should begin with an empty Spring Boot sample using the latest version of Gradle, which will eventually be the home for the project's minimal authorization server sample code. 

For simplicity, Java classes should be placed into a package called `sample`.

At this point, this sample doesn't need any MVC endpoints or other configurations.

**Comment by srempfer** [comment]
@omvandenberge: Oh just saw to late that you also working on the issue..
@jzheaux: I had a look on the spring-security project structure and linked a working branch to the issue. Is this something you had in mind?
