### ISSUE TITLE
the oauth2-integration sample of release 0.0.1 seems to be unworkable

### ISSUE THREAD

**Issue by yaozou** [spring-projects-experimental/spring-authorization-server#104]
For example, in the client module of the sample, looks like there's no request mapping for the redirect url (http://localhost:8080/authorized) defined in the below code

RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
        .clientId("messaging-client")
        .clientSecret("secret")
        .clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
        .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
        .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
        .redirectUri("http://localhost:8080/authorized")
        .scope("message.read")
        .scope("message.write")
        .build();

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope: message.read,message.write

This redirect url is likely handled by the application code instead of the spring security framework, right? Not sure if I understand it correctly. Could you please have a look? Thanks!

**Comment by liangyangtao** [comment]
english:

The redirect URI has returned the code to you. You can write an authorized method later

1 Exchange code post for accesstoken

2 Request with accesstoken http://localhost:8090/messages

中文：

redirect-uri 已经给你返回code 了，在client自己写一个authorized 方法就可以了

(1) 用code  post换取accesstoken

(2) 用accesstoken 请求http://localhost:8090/messages 就可以了

**Comment by yaozou** [comment]
> 
> 
> english:
> 
> The redirect URI has returned the code to you. You can write an authorized method later
> 
> 1 Exchange code post for accesstoken
> 
> 2 Request with accesstoken http://localhost:8090/messages
> 
> 中文：
> 
> redirect-uri 已经给你返回code 了，在client自己写一个authorized 方法就可以了
> 
> (1) 用code post换取accesstoken
> 
> (2) 用accesstoken 请求http://localhost:8090/messages 就可以了

Thanks! But this is not what I'm looking for. Acutally I know how oauth2 works, and I just  want to see the supposed best practices in spring security and spring authorization server. It would be great if the spring team could complete the sample if it's incomplete for now, so that we can quickly evalute the server in our use cases and eventually switch to it when it becomes more mature.

**Comment by jgrandja** [comment]
@yaozou 

As stated by @liangyangtao 

> The redirect URI has returned the code to you. You can write an authorized method later

This is correct.

The authorization code is returned to the client via the registered `redirect_uri` `{baseUrl}/authorized`, which in turn exchanges it for an access token. At the end of the `authorization_code` grant flow, the client will redirect to either the registered `redirect_uri` `{baseUrl}/authorized` OR the last saved request (which is what happens in the sample). See [OAuth2AuthorizationCodeGrantFilter](https://github.com/spring-projects/spring-security/blob/2abf59b695b3ad14719299ed17ff47b181eed802/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationCodeGrantFilter.java#L242).

Closing as this sample works as expected.
