### ISSUE TITLE
Improve naming of KeyManager and ManagedKey 

### ISSUE THREAD

**Issue by asaikali** [spring-projects-experimental/spring-authorization-server#105]
Currently the `KeyManager` interface has finder methods only it does not seem like a Manager class it is useful to consider renaming it to something like `KeySource`.  If the `KeyManager` it makes sense to rename `ManagedKey` at the same time, I think `KeyHolder`,`KeyInfo`,`KeyMaterials`, `KeyDeatils` are reasonable candidate names.

**Comment by jgrandja** [comment]
@asaikali 

`ManagedKey` is replaced by `CryptoKey` (subclasses `SymmetricKey` and `AsymmetricKey`)
`KeyManager` is replaced by `CryptoKeySource`

Let me know your thoughts.
