### ISSUE TITLE
Add docs skeleton to the project

### ISSUE THREAD

**Issue by asaikali** [spring-projects-experimental/spring-authorization-server#107]
Add the asciidoctor skeleton to the project so that docs can begin to be written in the style of typical spring projects.

**Comment by jgrandja** [comment]
@asaikali Here is the [starting point](https://github.com/spring-projects-experimental/spring-authorization-server/blob/master/docs/manual/src/docs/asciidoc/index.adoc) for the reference manual.

Build the docs by running `./gradlew clean docs`
