### ISSUE TITLE
Error package import

### ISSUE THREAD

**Issue by freeman0432** [spring-projects-experimental/spring-authorization-server#111]
https://github.com/spring-projects-experimental/spring-authorization-server/blob/e16f15cce33d3feab15637198aa8b81d1e08a6c8/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/jose/jws/NimbusJwsEncoder.java#L31

**Comment by jgrandja** [comment]
Thanks for the report @freeman0432.

`com.nimbusds:nimbus-jose-jwt:9.0` introduced breaking changes so for now we're going to stick with `8.+`.

This has been resolved in gh-113.
