### ISSUE TITLE
Basic clustered deployment support

### ISSUE THREAD

**Issue by yaozou** [spring-projects-experimental/spring-authorization-server#114]
Hi,

Could we expect that spring auth server provides OOTB support for clustered deployment recently, since HA is also pretty important for us to adopt the server in our experimental env?

Thanks!

**Comment by yaozou** [comment]
The server might be in an early stage, but we guess that it would be relatively easy for the spring team to support this feature, right? e.g.  provide redis-based implementations for something like AuthService, KeyManager, etc? Not sure if we understand it correctly

Thanks!

**Comment by john2morgan** [comment]
> The server might be in an early stage, but we guess that it would be relatively easy for the spring team to support this feature, right? e.g. provide redis-based implementations for something like AuthService, KeyManager, etc? Not sure if we understand it correctly
> 
> Thanks!

is it easy enough to diy?

**Comment by yaozou** [comment]
> 
> 
> > The server might be in an early stage, but we guess that it would be relatively easy for the spring team to support this feature, right? e.g. provide redis-based implementations for something like AuthService, KeyManager, etc? Not sure if we understand it correctly
> > Thanks!
> 
> is it easy enough to diy?

We guess it might not be that straightforward because we're not familiar with the whole picture？

Since we have to make a technical decision (about shiro, spring security, keycloak, spring auth server, etc) within this week, it would be appreciated if the spring team could give us some feedback!

**Comment by jgrandja** [comment]
@yaozou Spring Authorization Server will support a clustered deployment topology but will require a custom configuration based on your environment. The core components `RegisteredClientRepository`, `OAuth2AuthorizationService` and `KeyManager` (more to come) will need to be backed by implementations that support a clustered deployment, eg. a Redis service.

> e.g. provide redis-based implementations for something like AuthService, KeyManager, etc?

We haven't decided which backing implementations will be provided but you can always provide your own implementation of the mentioned interfaces and register them as a `@Bean`. The current implementations are in-memory so obviously these won't work in a clustered deployment.

We have many more core features that need to be implemented so these backing implementations are lower priority.
