### ISSUE TITLE
Token endpoint response error in the authorization code flow.

### ISSUE THREAD

**Issue by vincent-hsin** [spring-projects-experimental/spring-authorization-server#120]
**Describe the bug**
It response error when I request token endpoint  with code and client_id parameters in the authorization code flow. But it reponse the expected result without client_id parameters.

**To Reproduce**
{
    "error": "invalid_client"
}

**Expected behavior**
{
    "access_token": "eyJraWQiOiIzYjEzOTg3Yi05Mjk3LTRkOWQtOTdkOC02MWVlY2ZjMmFlZTQiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImF1ZCI6Im1lc3NhZ2luZy1jbGllbnQiLCJuYmYiOjE2MDA5NDA2MjIsInNjb3BlIjpbIm1lc3NhZ2UucmVhZCIsIm1lc3NhZ2Uud3JpdGUiXSwiaXNzIjoiaHR0cHM6XC9cL29hdXRoMi5wcm92aWRlci5jb20iLCJleHAiOjE2MDA5NDQyMjIsImlhdCI6MTYwMDk0MDYyMiwianRpIjoiYTg3ZWYwNTMtNjE0NC00NmI2LWI3M2YtZjJiMDA3NzYxNWE1In0.UsyIWPgODPIo-Ol5RmVt3tLUovBaFgJcKS4P2HJ7Cz6usNUG9UJUt_gATHAZ6CzDeFPTPw9zXwhRUGzCJChLfWSw-u6khvV91QwaB1sLzIsVEHR4tWNJULMsaaJLZtZz4BdP-_GHUFnxazxnPdpGqng035RbOoe7l8F0Ie9ObHIc2-H2MCaCIxbFbH7zpxsY2yStzUE0VILJnb8hi7kV8p3F7LsBrCM8f1SvwJR60VFoSIZhL7aaQVd9rfGpLNVgONadCEvFjHarN03JUcRUQG2YdDkDoul6MZtipnB8Cra1h9VFX7jn4vN7VPlel9HmFKLfeIVqNB2VBx7-EYEXwg",
    "scope": "message.read message.write",
    "token_type": "Bearer",
    "expires_in": "3600"
}

**Comment by lizhongyue248** [comment]
Please see https://github.com/spring-projects-experimental/spring-authorization-server/issues/102#issuecomment-680067393 .

He said invalid. I don't want to argue with him.

**Comment by vincent-hsin** [comment]
@lizhongyue248 Thank you. Seems to be a duplicate issue, I will look at your issue later.

**Comment by jgrandja** [comment]
@vincent-hsin It's not clear to me the issue you are having. Please provide more details if you want me to look into this issue. Detailed steps to reproduce or ideally a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by jgrandja** [comment]
Closing as per [comment](https://github.com/spring-projects-experimental/spring-authorization-server/pull/121#discussion_r494984942)
