### ISSUE TITLE
make OAuth2TokenEndpointFilter can be customized

### ISSUE THREAD

**Issue by wws19125** [spring-projects-experimental/spring-authorization-server#125]
**Expected Behavior**
just add something like setAuthorizationGrantAuthenticationConverter and so on, thus we can customize this one
**Current Behavior**
all was final or unmodifiableMap
**Context**

**Comment by jgrandja** [comment]
Thanks for the report @wws19125.

The ability to customize the token endpoint will be provided at a later point.

We are still in early development and not quite there as far as allowing for greater customization.

I'm going to close this but rest assured that customization capabilities will be added to a number of components within the framework.
