### ISSUE TITLE
"password" grant_type for token endpoint

### ISSUE THREAD

**Issue by amrutprabhu** [spring-projects-experimental/spring-authorization-server#126]
**Expected Behavior**
Password grant type is supported

**Current Behavior**
I see that the password grant type is not supported and throws an error when we make a request with password grant type. I saw there are only two converters. one for authorization code and one for client credentials. 

**Context**
It's not something that is blocking me. Its just that when I worked with spring-security-oauth2 library it worked. But it's not present in this library. 

**Question**
So is it somewhere on the road map to be implemented or waiting for contribution. Or is it not be supported by this library?

**Comment by jgrandja** [comment]
Thanks for reaching out @amrutprabhu. We will not be providing support for the `password` grant as its deprecated in OAuth 2.1. For reference, see [OAuth 2.1](https://oauth.net/2.1/) and [It's Time for OAuth 2.1](https://aaronparecki.com/2019/12/12/21/its-time-for-oauth-2-dot-1).

**Comment by akuma8** [comment]
I need this grant in my application and even deprecated, it would be nice to have it by default. I will try to implement it in my own following this guide: https://docs.spring.io/spring-authorization-server/docs/current/reference/html/guides/how-to-ext-grant-type.html

**Comment by akuma8** [comment]
@hartimcwildfly I agree with you, they should remove that constant.

**Comment by 3e-maciej** [comment]
Did anyone manage to implement PASSWORD grant type flow? any hints/snippets?
I think it is deprecated because best practices, but there should be at least manual how to achieve this flow for backward compatibility when updating legacy projects...

**Comment by hartimcwildfly** [comment]
My use case was to mock Auth0 for integration tests. For this I started to use this spring-authorization-server. In the end I went for a keycloak container which still supports password grant type.

**Comment by jgrandja** [comment]
@3e-maciej 

>  there should be at least manual how to achieve this flow for backward compatibility when updating legacy projects

See [How-to: Implement an Extension Authorization Grant Type](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-ext-grant-type.html), which demonstrates how you could implement the `password` grant type as an extension grant.
