### ISSUE TITLE
Provide a mechanism for setting claim values and adding custom claims on the access token

### ISSUE THREAD

**Issue by mstickel** [spring-projects-experimental/spring-authorization-server#127]
**Expected Behavior**
Authorization Server administrators should be able to configure claims and their values on the Access Token.  This includes setting the issuer (ISS) and time-to-live (EXP) claims which are already noted as TODO items in {{OAuth2AuthorizationCodeAuthenticationProvider}}.

**Current Behavior**
Currently, we can't set the issuer claim (hard-coded to https://oauth2.provider.com), the time-to-live (hard-coded to 1 hour), or add any custom claims (such as firstName, lastName, email, roles/permissions) to the token.

**Context**
No workarounds at this time.

**Comment by jgrandja** [comment]
Thanks for the report @mstickel.

The ability to add custom claims or modify the default claims is a minimum requirement.

We definitely plan on adding this capability for all token types: JWT, opaque and ID Token.

However, we're still in early development and not quite there as far as allowing for greater customization.

This will likely be added after (or during) the work on #52

I'm going to close this but rest assured this capability is absolutely mandatory and will be added along with a number of other customization capabilities.

**Comment by mstickel** [comment]
Thanks @jgrandja.  So I don't file redundant stuff like this again, is there a big picture roadmap that describes what's on the roadmap in the longer term?

**Comment by jgrandja** [comment]
@mstickel The ZenHub board outlines the feature roadmap. You can access the ZenHub board via the [Feature Planning](https://github.com/spring-projects-experimental/spring-authorization-server#feature-planning) section in project page.
