### ISSUE TITLE
Client Authentication Method: Post does not work

### ISSUE THREAD

**Issue by ZhuBicen** [spring-projects-experimental/spring-authorization-server#132]
**Describe the bug**
With a registed client, with ClientAuthenticationMethod.POST,  when getting the access token it always return 401

**To Reproduce**
1. Navigate to sample authroization server: `spring-authorization-server/samples/boot/oauth2-integration/authorizationserver/`
2. Change the resgistered client authentication method from Basic to Post
```
		RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
				.clientId("messaging-client")
				.clientSecret("secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.POST)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
				.redirectUri("http://localhost:8080/authorized")
				.scope("message.read")
				.scope("message.write")
				.clientSettings(clientSettings -> clientSettings.requireUserConsent(true))
				.build();
```
3. Start the Sample Authorazation server
4. Use PostMan OAuth2 client to get access token, config as below(Chose Client Authentication Method: Send Client credentials in body)
![image](https://user-images.githubusercontent.com/1465566/96073779-bb6b5e00-0ed9-11eb-80ec-daf38c03e0f7.png)
5. Click "Request Token"
6. "/oauth2/token" returns 401
![image](https://user-images.githubusercontent.com/1465566/96074049-44829500-0eda-11eb-9767-3402fe2806e6.png)

**Expected behavior**
"/oauth2/token" can return the token

**Sample**
in provided sample authorization server:
`spring-authorization-server/samples/boot/oauth2-integration/authorizationserver/`

**Comment by jgrandja** [comment]
Thanks for the report @ZhuBicen.

The only client authentication method currently supported is HTTP Basic.

I just logged #134 to support form POST.

I'll close this in favour of #134.
