### ISSUE TITLE
Introduce OAuth2Tokens

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#137]
We need to introduce a new construct called `OAuth2Tokens`, which will serve as a container for OAuth 2.0 Tokens. This should also be associated as a member in `OAuth2Authorization`.

**Comment by hamid646** [comment]
i'd be interested to take this

**Comment by jgrandja** [comment]
Thanks for the offer @hamid646.

I assigned this to myself and started working on it yesterday. I just finished and pushed.

Please keep an eye out for new issues.

Thanks again for your interest.
