### ISSUE TITLE
Using UserDetailsService directly for authentication and limiting available scopes

### ISSUE THREAD

**Issue by zokkr** [spring-projects-experimental/spring-authorization-server#147]
First of all: You guys are doing a great job. I was really happy when I read the announcement that Spring will get it's own auth server again!

**Expected Behavior**
To add to what's currently possible, tt would be great to have a functionality that allows (optionally) limiting the scopes a user can obtain from a client based on the authorities that user has.
For this, a UserDetailsService would have to be provided (as part of the RegisteredClient) that can provide the UserDetails with the respective GrantedAuthorities. Based on the scopes defined in the RegisteredClient, a scope should only be present as claim in case the Collection of the GrantedAuthorities contains that scope based on a String comparison.

In case a PasswordEncoder is provided too, checking the credentials for the auth code grant could happen using that UserDetailsService, so that there is no need to protect the authorization endpoint in the WebSecurityConfig.

**Current Behavior**
Scopes are hardcoded into a RegisteredClient with no possibility to control them based on the UserDetails' authorities.

Protecting the authorization endpoint in the WebSecurityConfig is needed in order for a secure auth code grant.
This has another negative side-effect: The OAuth2AuthorizationEndpointFilter is added before the AbstractPreAuthenticatedProcessingFilter. This means if there is no session, we can not give our credentials eg. via BasicAuth and fetch an auth code in the same request.

**Context**
I want to authenticate users and admins in the same UI. The access to specific parts of the application should be controlled by the scopes, so admins need to have more scopes than users - which is reflected by the GrantedAuthorities of the UserDetails.
Currently, the alternative would be to use different login UIs (or at least an option to select whether to log in as admin) and a very cumbersome configuration, because I would need different authorization endpoints so I can protect them differently in the WebSecurityConfig. An alternative to this last point is a filter that filters out requests to a specific client if the user does not have a specific GrantedAuthority.

**Comment by joshuatcasey** [comment]
@jgrandja The App SSO team is interested in this topic as well - we can discuss tomorrow

**Comment by jgrandja** [comment]
@zokkr 

> Functionality that allows (optionally) limiting the scopes a user can obtain from a client based on the authorities that user has

This is a custom configuration that would need to be applied in the application. The specifications do not outline a method for mapping scopes to user authorities. This is almost in all cases implemented as a custom configuration in the application. The goal of Spring Authorization Server is to implement to spec but also provide hooks to allow applications to customize beyond the specs.

> For this, a `UserDetailsService` would have to be provided (as part of the RegisteredClient) that can provide the UserDetails with the respective GrantedAuthorities

It doesn't make sense to require a `UserDetailsService` as some applications may configure a delegation-based authentication mechanism using a external provider, e.g. SAML or external OIDC provider.

FYI, you could configure a `UserDetailsService` in the [sample](https://github.com/spring-projects-experimental/spring-authorization-server/blob/master/samples/boot/oauth2-integration/authorizationserver/src/main/java/sample/config/AuthorizationServerConfig.java#L69) and you'll be able to customize scopes based on user authorities when #145 is merged as it will provide a hook to allow you to customize any claims in the JWT.
