### ISSUE TITLE
Make it possible to customize the issuer claim and the access token expiration time 

### ISSUE THREAD

**Issue by lhmoraes** [spring-projects-experimental/spring-authorization-server#148]
You guys are doing an amazing job and that is one of the most expected Spring project.

That is a simple feature request and please just let me know if you need more information.

Thanks

**Comment by lhmoraes** [comment]
You guys are doing an amazing job and that is one of the most expected Spring project.

That is a simple feature request and please just let me know if you need more information or if the team needs some help to build the server.

Thanks

**Comment by lspil** [comment]
Hello. I'm not developing in the project, but I've seen your question about the access token expiration time. From what I see, this can be already configured via: 

.tokenSettings(t -> {
          t.accessTokenTimeToLive(Duration.ofHours(1));
})

I don't see indeed something about the issuer yet.

**Comment by lhmoraes** [comment]
Hi @Ispil, its currently possible to configure the expiration token and the issuer claim, but there is no effect yet, they still using the default hard coded values

**Comment by jgrandja** [comment]
@lhmoraes @lspil Configuring the `issuer` is coming in #143 and the token expiration configuration will take effect in #145. Closing this as a duplicate.
