### ISSUE TITLE
Optimize the authentication server for production using  a non-blocking framework:  (Spring Webflux).

### ISSUE THREAD

**Issue by jhonToni** [spring-projects-experimental/spring-authorization-server#152]

**Comment by jgrandja** [comment]
@jhonToni We are strictly focusing on a Servlet implementation for the initial set of features that would qualify for a MVP version. We haven't decided whether we'll provide a WebFlux version at this point. 

Quite honestly, I'm not convinced it's needed. The client and resource server(s) are the most active, whereas, the authorization server is not as active as it simply issues a token and may validate a token, which is limited activity between the many interactions that follow between a client and resource server after a token is issued.

Either way, I'm going to close this issue as WebFlux is not on the roadmap as of now.

**Comment by krnbr** [comment]
@jgrandja can u help a little bit with the idea of how to convert all of this project to reactive?

In particular the filter part. Any initial pointers will help a lot

**Comment by SledgeHammer01** [comment]
@jgrandja Also, it's incompatible with embedding it in a webflux application.

**Comment by Crovitz** [comment]
support for that would be helpful especially when we consider modular monolith architecture

**Comment by dreamstar-enterprises** [comment]
Would be great to add support!

**Comment by vnobo** [comment]
I'm a stubborn guy, I hope to join, I'm willing to complete this part

**Comment by vnobo** [comment]
What a stubborn guy, I hope to join, I am willing to complete this part
