### ISSUE TITLE
Building the project fails

### ISSUE THREAD

**Issue by jhonToni** [spring-projects-experimental/spring-authorization-server#153]
**Describe the bug**
When I build the project with gradle throw an exception.

**The stack trace**

```
> Task :spring-security-oauth2-authorization-server:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-security-oauth2-authorization-server:compileJava'.
> Could not resolve all files for configuration ':spring-security-oauth2-authorization-server:compileClasspath'.
   > Could not resolve com.nimbusds:nimbus-jose-jwt:latest.release.
     Required by:
         project :spring-security-oauth2-authorization-server
      > Failed to list versions for com.nimbusds:nimbus-jose-jwt.
         > Unable to load Maven meta-data from https://repo.spring.io/libs-snapshot/com/nimbusds/nimbus-jose-jwt/maven-metadata.xml.
            > Could not HEAD 'https://repo.spring.io/libs-snapshot/com/nimbusds/nimbus-jose-jwt/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.nimbusds:nimbus-jose-jwt:latest.release.
     Required by:
         project :spring-security-oauth2-authorization-server > org.springframework.security:spring-security-oauth2-jose:5.4.2-SNAPSHOT:20201113.161825-38
      > Failed to list versions for com.nimbusds:nimbus-jose-jwt.
         > Unable to load Maven meta-data from https://repo.spring.io/libs-snapshot/com/nimbusds/nimbus-jose-jwt/maven-metadata.xml.
            > Could not HEAD 'https://repo.spring.io/libs-snapshot/com/nimbusds/nimbus-jose-jwt/maven-metadata.xml'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
1 actionable task: 1 executed
```

**Comment by rozagerardo** [comment]
I am experiencing a similar issue.
I think it might be related to the change mentioned here (programmed for November 12th, 2020):
https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020
If I get this correctly, it's a temporary issue.
Just in case, I'd like to confirm with you @jgrandja, as I am currently trying to wrap up https://github.com/spring-projects-experimental/spring-authorization-server/issues/52 and this is getting in the way :)

**Comment by bclozel** [comment]
Yes this is probably related. I ran a build (with my credentials) so you should be fine now with the missing artifacts.
Note that this is a temporary workaround, so we can't consider this issue solved yet.

I don't think the build should try and resolve those dependencies on `libs-snapshot`, but rather on maven central. In most Spring projects, the `repo.spring.io/snapshot` should be enough, but maybe there's something specific here that I'm not aware of.

**Comment by jgrandja** [comment]
@jhonToni @rozagerardo I just re-ran the build and it passed. It seems this might have been a temporary network related issue.

**Comment by jgrandja** [comment]
I'm re-opening this as the issue is related to what @rozagerardo mentioned in this [comment](https://github.com/spring-projects-experimental/spring-authorization-server/issues/153#issuecomment-727693549).

**Comment by jgrandja** [comment]
Resolved via 6db194d and 9f246fc

**Comment by jsamon** [comment]
> Resolved via [6db194d](https://github.com/spring-projects-experimental/spring-authorization-server/commit/6db194da2734fd5587534c8217aaf3a7a5f9a229) and [9f246fc](https://github.com/spring-projects-experimental/spring-authorization-server/commit/9f246fc30476388a94e7d967096792ee94bbd38b)

How can I create an account for repo.spring.io? I can’t login with my account in jFrog platform

**Comment by jgrandja** [comment]
@jsamon repo.spring.io is a private repository for the Spring organization so you won't be able to obtain your own credentials.

I just pushed some updates, which should allow you to build. Can you ensure you pull this latest commit 39ed8205608b18594fa8e0368f68ed9ecf8aef22 and try the build. Please let me know if it worked.

**Comment by jsamon** [comment]
> @jsamon repo.spring.io is a private repository for the Spring organization so you won't be able to obtain your own credentials.
> 
> I just pushed some updates, which should allow you to build. Can you ensure you pull this latest commit [39ed820](https://github.com/spring-projects-experimental/spring-authorization-server/commit/39ed8205608b18594fa8e0368f68ed9ecf8aef22) and try the build. Please let me know if it worked.

Yes it works! Thanks a lot!
