### ISSUE TITLE
Trying to request user authentication for an inexistent client doesn't show any custom exception

### ISSUE THREAD

**Issue by lspil** [spring-projects-experimental/spring-authorization-server#156]
Hi everyone,

Maybe this is more cosmetic, but if I try to use an inexistent client here:

http://localhost:8080/oauth2/authorize?response_type=code&client_id=client&scope=read

It redirects me to the error page and I have nothing in the console. Shouldn't we have at least an exception message for the poor developer trying to debug something like this? Now with small examples on an experimental implementation is easy to see what's wrong, but when this will be production-ready, out there in the jungle you might get really confused with this.

Thnks for your amazing work on this project!

**Comment by jgrandja** [comment]
Thanks for your feedback @lspil !

I'll close this in favour of #159.
