### ISSUE TITLE
Setting the expiration time for the access token doesn't work

### ISSUE THREAD

**Issue by lspil** [spring-projects-experimental/spring-authorization-server#157]
Hi team,

I have tried to use the token configuration method to set an expiration time for the access token. I have configured an expiration for a duration of 5 hours, but the access token still seems to expire in one hour. Here is an example of the way I set up the project:

https://github.com/lspil/youtubechannel/tree/master/experimental-as-v003

When I configured:

.tokenSettings(t -> {
          t.accessTokenTimeToLive(Duration.ofHours(5));
        })

My expectation was to see the JWT token exp time in 5 hours starting with the generation. It however defaults always to one hour.

**Comment by jgrandja** [comment]
@lspil The token expiration configuration will take effect in #145. Closing this as a duplicate.
