### ISSUE TITLE
Ensure refresh token is not revoked

### ISSUE THREAD

**Issue by lspil** [spring-projects-experimental/spring-authorization-server#158]
Hi Team,

I generate a refresh token and I have the configuration setup that this refresh token can be reused:

.tokenSettings(t -> {
          t.enableRefreshTokens(true);
          t.reuseRefreshTokens(true);
 })

I then call the revoke endpoint:

http://localhost:8080/oauth2/revoke?token_type_hint=refresh_token&token=Sk8LIWSrP-7Rij9Z-lN5-v6i54GslkzWnp-g_lkCz9py6QVosriMqslkVnzQ8XymAQfsuWBiFR5KivpKTGI1TanFA-GyL-7ScFD2A7HC2ltzuHpu92a-VieWk_X1ILnI

I get back a 200 OK, so I expect the token has been revoked and I cannot use it anymore to generate access tokens. However, It seems I can still generate as many access tokens as I'd like. 

From my point of view is either a problem on the revoke endpoint which shouldn't maybe return me 200 OK if revocation didn't work for any reason or a problem with the revocation itself.

Here is a project example: https://github.com/lspil/youtubechannel/tree/master/experimental-as-v003

**Comment by jgrandja** [comment]
@lspil The [example](https://github.com/lspil/youtubechannel/tree/master/experimental-as-v003) you provided does not provide a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example). For future reference, please ensure the sample you provide has either a test and steps to reproduce the error.

Either way, I took a look at `OAuth2RefreshTokenAuthenticationProvider` and it's missing a check that is similar to what we have in [OAuth2AuthorizationCodeAuthenticationProvider](https://github.com/spring-projects-experimental/spring-authorization-server/blob/9818618ea3c821e46501760efa6655d5ea33e5d9/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeAuthenticationProvider.java#L115). So indeed this is a bug. Thanks for reporting this! Would you be interested in submitting a fix for this?

**Comment by lspil** [comment]
Hey. Yes. Sorry. I'll try to be more specific next time when I report something. I should have specified at least a set of steps :)

**Comment by jgrandja** [comment]
No worries @lspil. Thanks for taking on this issue!
