### ISSUE TITLE
Setup GitHub Actions workflow for PRs

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#16]
When a PR is submitted, we should test any changes by running the build.
The status of build should appear in the UI for the pull request.

**Comment by kratostaine** [comment]
@jgrandja Thoughts about using GitHub Actions instead of Travis?

**Comment by kratostaine** [comment]
Ah I see there's already a workflow config added [here](https://github.com/spring-projects-experimental/spring-authorization-server/blob/master/.github/workflows/continuous-integration-workflow.yml)

**Comment by dfcoffin** [comment]
Is this still an open issue, since a GitHub Actions workflow has already been added?

**Comment by jgrandja** [comment]
@eleftherias Should we close this since you setup #11 ? I'm assuming GitHub actions will build incoming PR's?

**Comment by eleftherias** [comment]
@jgrandja I haven't set up a workflow for PRs. It only builds on commits currently

**Comment by kratostaine** [comment]
I feel this issue can be edited as Update GitHub workflow for CI instead of having Travis.

**Comment by jgrandja** [comment]
@eleftherias What do you suggest? Should we use GitHub actions for building PR's or Travis?

**Comment by eleftherias** [comment]
I suggest using a GitHub Actions workflow for building PRs as well. It integrates well and it will be nice to have everything in on place.

If someone from the community is interested in contributing to this, I can work with you on it.
Make sure to comment below claiming this issue to avoid duplicating work.

**Comment by kratostaine** [comment]
@eleftherias I am interested in working on this. May I take this up?

**Comment by eleftherias** [comment]
@kratostaine Thank you, the issue is yours. Feel free to reach out if you have any questions.
