### ISSUE TITLE
Cutomize the UserConsentPage or support setRedirectUrl .

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-projects-experimental/spring-authorization-server#164]
In OAuth2 authorization code login，the page is static string：
```
this.authorizationService.save(authorization);

// TODO Need to remove 'in-flight' authorization if consent step is not completed (e.g. approved or cancelled)

UserConsentPage.displayConsent(request, response, registeredClient, authorization);
```
But i want set my own page .
I know the project is in devoping , So can we support the feature by some simple way ? 
Such as some code like this:
```
UserConsentService.display()
or 
UserConsentService.redirect()
```

UserConsentService is something like for support configed by developer users .

**Comment by jgrandja** [comment]
@andyzhaozhao The ability to customize the User Consent has been logged in #139. Closing as duplicate.
