### ISSUE TITLE
Allow configuration for the issued JWTs

### ISSUE THREAD

**Issue by annabast** [spring-projects-experimental/spring-authorization-server#166]
**Expected Behavior**

While doing the configuration of the authorization server, there should be a way to set claims of the JWT to unique values that better reflect what the JWT's are being used for. For example, there should be a way to change the issuer from "https://oauth2.provider.com" to "https://myissuer.com"

**Current Behavior**

Currently the issuer and time to live are hard coded into org.springframework.security.oauth2.server.authorization.authentication.OAuth2TokenIssuerUtil.

**Context**

By being able to customize the issuer, a resource server can accept JWTs from multiple different Spring Security OAuth2 Authorization Servers.

**Comment by jgrandja** [comment]
@annabast This customization is coming in #143 and #145
