### ISSUE TITLE
Epic: Setup repository

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#17]
This epic groups the issues/tasks we should strive to complete before we publish the blog post.

**Comment by dfcoffin** [comment]
Should the repository use the same schema as the current spring-security-oauth project?  What database implementation does the project need to support (H2, Postgresql, MySQL, etc.)

**Comment by jgrandja** [comment]
@dfcoffin The repository being referred to in this issue is the GitHub repository.

Also, this intention of this new project is to re-write Authorization Server. We have no plans on reusing existing code from Spring Security OAuth.

**Comment by dfcoffin** [comment]
@jgrandja Thanks for the clarification

**Comment by paurav-munshi** [comment]
Are we considering Spring Reactive for this ? What are the thoughts of the team around them ? Since this would be highly io intensive, this seems to be an ideal candidate for reactive architecture.

**Comment by rwinch** [comment]
@paurav-munshi At this time we are focused on imperative style applications.
