### ISSUE TITLE
Configured TokenSettings.accessTokenTimeToLive() not used

### ISSUE THREAD

**Issue by momrak** [spring-projects-experimental/spring-authorization-server#172]
**Describe the bug**
Default and custom tokenSettings regarding time to live does not seem to be applied

**To Reproduce**
I am trying out the sample authorization server, client and resource server. In the `AuthorizationServerConfig` i tried setting the `.tokenSettings(tokenSettings -> tokenSettings.accessTokenTimeToLive(Duration.ofSeconds(20)))`, and then debug the clients `authorizationCodeGrant` method to see the access and refresh token. I would then expect the difference between `issuedAt` and `expiresAt` to be 20 minutes. However it was always 1 hour. I then also tried this while not configuring the tokenTimeToLive, and the same duration was set then. I was able to disable the refresh token, so some of the settings seems to work.

**Expected behavior**
When setting `.tokenSettings(tokenSettings -> tokenSettings.accessTokenTimeToLive(Duration.ofSeconds(20)))` i expect the accessToken to have a validity of 20 sec. Same when configuring the refresh token. And if not configuring anything I expect to see default values of 5 and 60 mins respectively.

**Sample**
I used your sample repository. In the added screenshot you can see a photo of the debug session. I might have missed something  here regarding the customization, but I am not able to figure out, so I decided to report this.
![authServer](https://user-images.githubusercontent.com/6552049/101288449-e77acf80-37f6-11eb-9c89-b7237802eb63.png)

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by momrak** [comment]
The attached image shows a debugging session from when I did not configure the tokenSettings, so the default values were expected

**Comment by jgrandja** [comment]
Thanks for the report @momrak. This is now fixed via f077337
