### ISSUE TITLE
Use ProviderSettings in OAuth2AuthorizationServerConfigurer

### ISSUE THREAD

**Issue by florianberthe** [spring-projects-experimental/spring-authorization-server#182]
Hello,

Happy new year !

I probably found a bug in OAuth2AuthorizationServerConfigurer class. 
The tokenEndpoint and tokenRevocationEndpoint properties from ProviderSettings are not used in OAuth2ClientAuthenticationFilter for :
- creation of OAuth2ClientAuthenticationFilter
- creation of DelegatingAuthenticationEntryPoint

As a result, using custom urls for both endpoints doesn't work at all.

Thank you for your support.

Flo

**Comment by jgrandja** [comment]
Thanks for the report @florianberthe.

Maybe you missed the [comment](https://github.com/spring-projects-experimental/spring-authorization-server/blob/36e66bd732303bf1a057e09fca4956643b929f4b/oauth2-authorization-server/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2AuthorizationServerConfigurer.java#L153) in the code?

I'm planning on resolving this in the upcoming 0.1.0 release.

**Comment by florianberthe** [comment]
@jgrandja I've already read the comment before but as it is only written in _getEndpointMatchers()_, I prefered creating an issue then a fix.
