### ISSUE TITLE
Epic: Add Client Credentials Grant sample

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#19]
This epic groups all the issues that will deliver a Spring Boot sample realizing the `client_credentials` grant flow.

Please review the [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4) to gain an understanding of the flow.

**Comment by andifalk** [comment]
According to https://tools.ietf.org/html/rfc6749#section-2.3.1 authentication can be done via
- HTTP Basic authentication scheme (MUST be supported)
- including the client credentials (client_id, client_secret) in the request-body (MAY be supported)

What is the plan here? Will just option 1 be implemented? Supporting both options would be more complicated as a simple basic auth filter will not work here.

**Comment by jgrandja** [comment]
@andifalk We'll start with HTTP Basic but we'll definitely need a strategy that will allow for other authentication mechanisms. Let's start simple and build from there.

**Comment by lspil** [comment]
@jgrandja If I can help for this implementation let me know :)

**Comment by jgrandja** [comment]
Thanks for reaching out @lspil ! Would you be interested in trying #5?
