### ISSUE TITLE
No CryptoKeySource clas in the version 0.0.3

### ISSUE THREAD

**Issue by 12ozCode** [spring-projects-experimental/spring-authorization-server#193]
I tried to use the last version of library from there: https://mvnrepository.com/artifact/org.springframework.security.experimental/spring-security-oauth2-authorization-server/0.0.3
After, I tried to try to run the sample app (samples/boot/oauth2-integration/authorizationserver) but faced a problem:
AuthorizationServer example uses CryptoKeySource class (sample/config/AuthorizationServerConfig.java:64), but there is no such class in the version 0.0.3

**Comment by jgrandja** [comment]
@12ozCode `CryptoKeySource` is new in 0.1.0. However, it was just removed via #196. Please use latest `master` or wait until `0.1.0` is released at end of month.
