### ISSUE TITLE
gradle build with 0.0.3 but I get many dependencies error, how can i resolve it?

### ISSUE THREAD

**Issue by BestLalaVm** [spring-projects-experimental/spring-authorization-server#194]
When I execute "gradle build" on source root directory, I get below error. How can i resolve it? many thanks.

What went wrong:
Execution failed for task ':spring-security-oauth2-authorization-server:compileJava'.
> Could not resolve all files for configuration ':spring-security-oauth2-authorization-server:compileClasspath'.
   > Did not resolve 'org.springframework:spring-jcl:5.3.0' which has been forced / substituted to a different vers
ion: '5.3.3'
   > Did not resolve 'org.springframework:spring-aop:5.3.0' which has been forced / substituted to a different vers
ion: '5.3.3'
   > Did not resolve 'org.springframework.security:spring-security-oauth2-core:5.4.1' which has been forced / subst
ituted to a different version: '5.4.2'
   > Did not resolve 'org.springframework.security:spring-security-config:5.4.1' which has been forced / substitute
d to a different version: '5.4.2'
   > Did not resolve 'com.fasterxml.jackson.core:jackson-databind:2.12.0-rc1' which has been forced / substituted t
o a different version: '2.12.1'
   > Did not resolve 'org.springframework.security:spring-security-web:5.4.1' which has been forced / substituted t
o a different version: '5.4.2'
   > Did not resolve 'org.springframework:spring-expression:5.3.0' which has been forced / substituted to a differe
nt version: '5.3.3'
   > Did not resolve 'com.fasterxml.jackson:jackson-bom:2.12.0-rc1' which is part of the dependency lock state
   > Did not resolve 'com.fasterxml.jackson.core:jackson-core:2.12.0-rc1' which has been forced / substituted to a
different version: '2.12.1'
   > Did not resolve 'org.springframework:spring-core:5.3.0' which has been forced / substituted to a different ver
sion: '5.3.3'
   > Did not resolve 'org.springframework.security:spring-security-oauth2-jose:5.4.1' which has been forced / subst
ituted to a different version: '5.4.2'
   > Did not resolve 'org.springframework:spring-web:5.3.0' which has been forced / substituted to a different vers
ion: '5.3.3'
   > Did not resolve 'com.fasterxml.jackson.core:jackson-annotations:2.12.0-rc1' which has been forced / substitute
d to a different version: '2.12.1'
   > Did not resolve 'com.nimbusds:nimbus-jose-jwt:9.1.2' which has been forced / substituted to a different versio
n: '9.4.1'
   > Did not resolve 'org.springframework:spring-context:5.3.0' which has been forced / substituted to a different
version: '5.3.3'
   > Did not resolve 'org.springframework.security:spring-security-core:5.4.1' which has been forced / substituted
to a different version: '5.4.2'
   > Did not resolve 'org.springframework:spring-beans:5.3.0' which has been forced / substituted to a different ve
rsion: '5.3.3'
   > Could not resolve com.fasterxml.jackson:jackson-bom:2.12.0-rc1.
     Required by:
         project :spring-security-oauth2-authorization-server
      > Could not resolve com.fasterxml.jackson:jackson-bom:2.12.0-rc1.
         > Could not get resource 'https://repo.spring.io/libs-release/com/fasterxml/jackson/jackson-bom/2.12.0-rc1
/jackson-bom-2.12.0-rc1.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-release/com/fasterxml/jackson/jackson-bom/2.12.0-rc1/jack
son-bom-2.12.0-rc1.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.fasterxml.jackson:jackson-bom:2.12.0-rc1.
     Required by:
         project :spring-security-oauth2-authorization-server > com.fasterxml.jackson.core:jackson-databind:2.12.1
         project :spring-security-oauth2-authorization-server > com.fasterxml.jackson.core:jackson-annotations:2.12
.1
         project :spring-security-oauth2-authorization-server > com.fasterxml.jackson.core:jackson-core:2.12.1
      > Could not resolve com.fasterxml.jackson:jackson-bom:2.12.0-rc1.
         > Could not get resource 'https://repo.spring.io/libs-release/com/fasterxml/jackson/jackson-bom/2.12.0-rc1
/jackson-bom-2.12.0-rc1.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-release/com/fasterxml/jackson/jackson-bom/2.12.0-rc1/jack
son-bom-2.12.0-rc1.pom'. Received status code 401 from server: Unauthorized

**Comment by jgrandja** [comment]
@BestLalaVm We are looking into this now. It's related to the [Permissions Changes to repo.spring.io](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020)

**Comment by jgrandja** [comment]
Related #191

**Comment by jgrandja** [comment]
@BestLalaVm As a result of the [changes made](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020) to the Spring Artifactory instance (repo.spring.io), the builds will not work for release tags 0.0.3 or previous.

Either way, please use the latest release 0.1.0 or master as there have been many changes to the codebase.
