### ISSUE TITLE
Support an audit event framework

### ISSUE THREAD

**Issue by joshuatcasey** [spring-projects-experimental/spring-authorization-server#203]
**Expected Behavior**
Spring Authorization Server should publish specific events for:
- Token issued
- Token revoked
- Token request rejected
This could happen for a few reasons:
  - Client does not have the requested scopes
  - Authorization code has already expired
- User consents to scopes
- Client is registered (#189)

Events generated should have the following information:
- client registrationId or `ClientRegistration`
- username (for user tokens) or `Authentication`
- list of scopes (issued in token, requested if rejected, or consented to)
- IP address of request

**Current Behavior**
Currently Spring Auth Server will generate two events for a token issuance:
-  `AuthenticationSuccessEvent` with source type `OAuth2ClientAuthenticationToken` 
- `AuthenticationSuccessEvent` with source type `OAuth2AccessTokenAuthenticationToken`

**Context**
`sso4k8s` has some auditing ideas in our [Helm Chart Docs](https://github.com/pivotal/sso4k8s-helm/blob/main/docs/AUDITING.md) (note that this repo is private)).

**Comment by jgrandja** [comment]
@joshuatcasey Would you (or your team) be interested in submitting a PR for this?

**Comment by joshuatcasey** [comment]
@jgrandja The short answer is yes. The `sso4k8s` devs (@fhanik and @Kehrlann and me) will work together on it.

**Comment by jgrandja** [comment]
Great. I will assign the ticket to you and we can all work together to realize this feature.

**Comment by jgrandja** [comment]
Closing as per [comment](https://github.com/spring-projects-experimental/spring-authorization-server/pull/217#issuecomment-796893680)
