### ISSUE TITLE
Client Secret Post Authentication not working (missing classes/commits from release build)

### ISSUE THREAD

**Issue by pangyiwei** [spring-projects-experimental/spring-authorization-server#204]
**Describe the bug**
When authenticating with the token endpoint, I am unable to configure client post authentication.

When creating the registered client, but using `clientAuthenticationMethod(ClientAuthenticationMethod.POST)`, the token endpoint client authentication still defaults to Basic authentication.

I did some debugging and found that `ClientSecretPostAuthenticationConverter` class is missing from the 0.0.3 release when it should have already been added since [0.0.2](https://github.com/spring-projects-experimental/spring-authorization-server/commit/e1f491bd61d8c0844ea7b766d44a998786b439e0)

Have downloaded the release source to check and the corresponding java files were indeed not present, they are however present on the master branch. Seems like that commit was not included in the release.

**To Reproduce**
1. Configure client post authentication for the token endpoint using `clientAuthenticationMethod(ClientAuthenticationMethod.POST)`.

2. Perform authorization code flow.

3. When invoking the token endpoint, client_id and client_secret in the POST data result in 401 error. The authentication is defaulted to basic authentication.

4. Download the release source code for [version 0.0.3](https://github.com/spring-projects-experimental/spring-authorization-server/releases/tag/0.0.3). And look for the file: `spring-authorization-server-0.0.3\oauth2-authorization-server\src\main\java\org\springframework\security\oauth2\server\authorization\web\ClientSecretPostAuthenticationConverter.java`. It should be present, but it is not.

**Expected behavior**
1. Perform step 1 and 2 as above, token endpoint can be invoked when client_id and client_secret are given in the POST request parameters.

2. The file `spring-authorization-server-0.0.3\oauth2-authorization-server\src\main\java\org\springframework\security\oauth2\server\authorization\web\ClientSecretPostAuthenticationConverter.java` should be present in the release build.

**Comment by jgrandja** [comment]
@pangyiwei `ClientSecretPostAuthenticationConverter` is in master and is targeted for the upcoming 0.1.0 release. See #134
