### ISSUE TITLE
Wiki Home and Feature List show raw HTML content when viewed with Chrome browser

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects-experimental/spring-authorization-server#241]
**Describe the bug**
When accessing the project's Wiki section the Home and Feature List pages do not properly format.  Rather than viewing formatted content, the browser displays the raw HTML coding

**To Reproduce**
Access the web pages:
https://github.com/spring-projects-experimental/spring-authorization-server/wiki
https://github.com/spring-projects-experimental/spring-authorization-server/wiki/Feature-List

**Expected behavior**
The web pages should show properly formatted data as shown on the OAuth 2.0 Specification web page of the Wiki:
https://github.com/spring-projects-experimental/spring-authorization-server/wiki/OAuth-2.0-Specifications

**Sample**

Sample is not needed.  Following the provided HTTPS links to see the problem.  All mentioned web pages showing the issue have been updated in the past 6 hours and

**Comment by jgrandja** [comment]
@dfcoffin I was converting the wiki pages from Markdown to asciidoc format and some weird behaviour was happening at random times. Seems the wiki is a bit flaky. Sometimes it would render correctly and other times it wouldn't. Keeping the Home page as markdown and converting Feature List and Spec pages to asciidoc seems to work fine now.
