### ISSUE TITLE
Spring Authorization Server is compatible with Spring Boot 2.3.2.release？

### ISSUE THREAD

**Issue by qq329401134** [spring-projects-experimental/spring-authorization-server#247]
Spring Authorization Server how to compatible with Spring Boot 2.3.2.release？ @jgrandja

**Comment by jgrandja** [comment]
@qq329401134 The [sample](https://github.com/spring-projects-experimental/spring-authorization-server/tree/master/samples/boot/oauth2-integration) is using [2.4.2](https://github.com/spring-projects-experimental/spring-authorization-server/blob/master/gradle.properties#L2)
