### ISSUE TITLE
Add Authorization Code Grant sample

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects-experimental/spring-authorization-server#25]
This sample should integrate with `spring-security-oauth2-client` and `spring-security-oauth2-resource-server`.

**Comment by andifalk** [comment]
I would definitely add PKCE as a requirement here.

**Comment by jgrandja** [comment]
@dfcoffin Can you please provide details on this issue.

**Comment by dfcoffin** [comment]
@andifalk Yes, I mean the authorization code grant.  I attempted to create an epic but was unable to post it, so I provided the Feature issue.  We can add an authorization code grant epic and reference it here.

I agree the authorization grand also should support PKCE, as an optional value and will update the request.  I used the Authorization Code Grant section of RFC 6749 to define the issue, without also referencing the additional RFCs that have been adopted since the publication of RFC 6749.

Perhaps a possible approach is to define an epic for each of the OAuth 2.0 "stand-alone" RFC and then issues can be tied to them.

**Comment by jgrandja** [comment]
@dfcoffin @andifalk Yes, the plan is to group a major feature using epics. I'm actually planning on logging a bunch of issues for the `authorization_code`  grant and grouping it into this epic. However, our goal really is to flush out #19 first and then work on `authorization_code`. That may change though if we have contributors working on both flows :)

**Comment by dfcoffin** [comment]
@jgrandja Is the plan to continue tracking this project in the spring-security-oauth Gitter channel or will there be a spring-authorization-server channel established since spring-security-oauth is actively being implemented and will be supported by Pivotal until March 2021, I believe.

**Comment by jgrandja** [comment]
Good question. Let me run it by the team and see if it makes sense to setup a new Gitter channel.
