### ISSUE TITLE
Can we have password grant type flow?

### ISSUE THREAD

**Issue by xuningfans** [spring-projects-experimental/spring-authorization-server#259]
I found password grant type in org.springframework.security.oauth2.core.AuthorizationGrantType#PASSWORD, but it does not have a implement, is it my mistake or it will coming soon？

**Comment by jgrandja** [comment]
Close as duplicate #115 . See [comment](https://github.com/spring-projects-experimental/spring-authorization-server/pull/115#issuecomment-696009503)
