### ISSUE TITLE
Provide the ability to customize AuthenticationEntryPoint

### ISSUE THREAD

**Issue by pstetsuk** [spring-projects-experimental/spring-authorization-server#260]
**Expected Behavior**
Need to have an ability to customize login URL

**Current Behavior**
`/login` always used for login

**Comment by jgrandja** [comment]
@pstetsuk 

This is already possible.

See below which provides default Authorization Server configuration and `HttpSecurity` for further customization.

```java
@Configuration(proxyBeanMethods = false)
public class AuthorizationServerConfig {

	@EnableWebSecurity
	public class AuthorizationServerSecurity extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);

			// TODO Configure authenticationEntryPoint
			AuthenticationEntryPoint authenticationEntryPoint = null;
			http
				.exceptionHandling()
					.authenticationEntryPoint(authenticationEntryPoint);
		}
	}

	...

	// Other @Bean's 


```

**Comment by pstetsuk** [comment]
It doesn't work. `OAuth2AuthorizationServerConfigurer` overwrite the changes in `configure()` because it applied later.  
The only possible way to overwrite it is create additional customizer and apply it after `OAuth2AuthorizationServerConfigurer`.  

But much easy way is create a  `AuthenticationEntryPoint` bean and then use it as default entry point in `OAuth2AuthorizationServerConfigurer`

**Comment by jgrandja** [comment]
@pstetsuk If you're still having an issue, please create a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) and share it via GitHub. This will allow me to see your exact configuration and provide a solution.

**Comment by pstetsuk** [comment]
@jgrandja I've create PR. There are 2 commits. In the first I added test to show that the approach you suggested doesn't work. In the second I added fix this issue.

**Comment by jgrandja** [comment]
@pstetsuk Thanks for providing the sample. This demonstrated a bug in `OAuth2AuthorizationServerConfigurer`, which is now resolved in gh-267.

You can now configure a custom `AuthenticationEntryPoint` using standard Spring Security configuration, e.g. `formLogin.loginPage("/login/custom")`.

I'm going to close your PR as those changes are not needed.

Thanks for reporting this issue!

**Comment by jgrandja** [comment]
Duplicate of gh-267
