### ISSUE TITLE
Provide JDBC implementation of RegisteredClientRepository

### ISSUE THREAD

**Issue by rlewczuk** [spring-projects-experimental/spring-authorization-server#265]
This would be useful in real-world workloads where clients are registered and maintained at runtime, without restarting server.

In fact, I've implemented it as I'm evaluating new spring authorization server in my (not-yet-production) projects. It follows  `userdetails.jdbc.JdbcDaoImpl` implementation and only uses Spring `JdbcTemplate`. 

If there are no objections, I would be happy to submit pull request when right time comes.

Current implementation: https://github.com/rlewczuk/spring-authorization-server/tree/gh-265-jdbc-client-repository

Related gh-57 gh-245

**Comment by jgrandja** [comment]
Thanks @rlewczuk. I've scheduled this for `0.1.2` so we can implement alongside gh-245.

Please see the comment in gh-245 related to `JdbcOAuth2AuthorizedClientService`.

Feel free to submit the PR after we get `0.1.1` out.
Thanks!

**Comment by metacubed** [comment]
@rlewczuk, what are your thoughts on.using the `ARRAY` database type for the `scopes` and `authorities` columns? It makes it easier to query/filter scopes during token generation.

**Comment by zhangzp-handsome** [comment]
@rlewczuk 
Why did you add two more `AuthorizationGrantType` and `ClientAuthenticationMethod` types ? Where can i get more information?

About:

```java
public static final AuthorizationGrantType JWT_BEARER = new AuthorizationGrantType("urn:ietf:params:oauth:grant-type:jwt-bearer");

public static final AuthorizationGrantType SAML2_BEARER = new AuthorizationGrantType("urn:ietf:params:oauth:grant-type:saml2-bearer");
```

**Comment by xzxiaoshan** [comment]
Current implementation: https://github.com/rlewczuk/spring-authorization-server/tree/gh-265-jdbc-client-repository

----------

@rlewczuk 

Refer to the previous official table definition rule: 
spring-security-oauth2-client-5.4.5.jar/org.springframework.security.oauth2.client/oauth2-client-schema.sql

It is indicated that the best choice is `oauth2_` For prefixes, intuitive semantics are recommended for field names, so the following suggestions are made:

It is recommended to modify the name and field of the table as follows:

1. Change the table name `clients` to `oauth2_ registered_ client`
2. Modify column `atoken_ttl` is `access_token_ttl`
3. Modify column `rtoken_ttl` is `refresh_token_ttl`
4. Modify column `rtoken_reuse` is `refresh_token_reuse`

**Comment by rlewczuk** [comment]
@xzxiaoshan Database object names have been fixed. Thank you for review.
