### ISSUE TITLE
Why did the revoke endpoint not trigger the remove method

### ISSUE THREAD

**Issue by lu-cheng** [spring-projects-experimental/spring-authorization-server#268]
Why did the revoke endpoint not trigger the remove method.

http://localhost:9000/oauth2/revoke

InMemoryOAuth2AuthorizationService
```java
	public void remove(OAuth2Authorization authorization) {
		Assert.notNull(authorization, "authorization cannot be null");
		this.authorizations.remove(authorization.getId(), authorization);
	}

**Comment by jgrandja** [comment]
@lu-cheng The client needs to authenticate in order to be able to revoke a token. Please see usage in the integration tests in `OAuth2TokenRevocationTests`.
