### ISSUE TITLE
What can I do for spring-authorization-server?

### ISSUE THREAD

**Issue by littlefisher666** [spring-projects-experimental/spring-authorization-server#269]
I want to do something for spring-authorization-server, what can I do?
I know what the OAuth2.0 is and I used the spring-security-oauth2 in my company code which create the new grant type.  I think maybe I can do something for spring-authorization-server.
I hope the spring-authorization-server release the code as soon as possible, because I don't want to use the deprecated code.

**Comment by lanmingle** [comment]
我觉得这个起码需要到 0.1.2 版本才可以使用，主要来源于 #245 这个实现，对于源码阅读多几次就会觉得其实没啥变化，使用难度不大，添加多几个过滤器，如果有问题或者不满足需要可以覆盖实现。

**Comment by lanmingle** [comment]
另外这个是开源~请把说词换一下。

**Comment by littlefisher666** [comment]
@lanmingle 因为我这边在使用spring-security-oauth2的时候，遇到了一些不太好扩展的地方，所以如果有机会参与项目的话，借此机会对我遇到的问题进行优化。另外“请把说词换一下”指的是什么？我是希望对这个项目提供帮助，而非对个人的

**Comment by jgrandja** [comment]
@littlefisher666 The best place to start is [Getting Started](https://github.com/spring-projects-experimental/spring-authorization-server#getting-started) and [Feature Planning](https://github.com/spring-projects-experimental/spring-authorization-server#feature-planning) outlines the feature roadmap.
