### ISSUE TITLE
Add OpenID Connect Discovery Endpoint

### ISSUE THREAD

**Issue by andifalk** [spring-projects-experimental/spring-authorization-server#27]
An authorization server should support the `/.well-known/openid-configuration` endpoint as specified by https://openid.net/specs/openid-connect-discovery-1_0.html.

This enables automatic client configuration (as already implemented in spring security 5) and we can also integrate JWKS endpoint as of gh-2.

The [Nimbus SDK](https://connect2id.com/products/nimbus-oauth-openid-connect-sdk) may be used for generating the endpoint response.

**Comment by dfcoffin** [comment]
This is also required to support #30 as it calls this endpoint.

**Comment by anoopgarlapati** [comment]
Hi @rwinch @jgrandja Can I work on this issue?
I'm a developer at VMware in Workspace ONE authorization server team and I have experience in developing applications on top of Spring Security.

**Comment by jgrandja** [comment]
@anoopgarlapati Thank you for the offer! Let's find another task for you to contribute as this one is lower on the priority. We need to focus on implementing core OAuth 2.0 before we get into OpenID Connect 1.0.

I'm in the process of putting together a roadmap that will prioritize the features to be developed. I will log an issue that provides a link to the roadmap along with the first set of epics and associated issues. 

Please take a look at the next set of issues (coming this week) and let me know which ones interest you and we can assign to you.

Sounds good?

**Comment by anoopgarlapati** [comment]
@jgrandja Sounds good and I understand. Looking forward to contributing. Thanks!

**Comment by jgrandja** [comment]
@andifalk I couldn't find a way to convert this issue to an epic so I'll close this in favour of #55.
