### ISSUE TITLE
Implicit grant 

### ISSUE THREAD

**Issue by m-pavel** [spring-projects-experimental/spring-authorization-server#278]
In according to https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix Implicit grant is not going to be implemented. 
But, I think design should allow to implement it (or whatever response type I need).
Currently 'response_type' is hardcoded in OAuth2AuthorizationEndpointFilter and I don't see how to add implicit flow support in my server without re-writing lot of code.

**Comment by Benzenes** [comment]
The Implicit grant is not recommended to use. (https://oauth.net/2/grant-types/implicit/); duplicate issue, see [comment](https://github.com/spring-projects-experimental/spring-authorization-server/pull/115#issuecomment-709558240)

**Comment by jgrandja** [comment]
@m-pavel Regarding your comment:

> I think design should allow to implement it (or whatever response type I need)

Customization hooks will be coming at a later point. See gh-139

> Customizing the Authorization Response

Closing this as duplicate
