### ISSUE TITLE
List of OAuth 2.0 RFC Standards

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects-experimental/spring-authorization-server#28]
Here is a list of the currently published IETF OAuth 2.0 standards and their status:

![image](https://user-images.githubusercontent.com/1829699/79536392-f2a5a300-804d-11ea-831e-b96ea12c7385.png)

**Comment by jgrandja** [comment]
@dfcoffin I provided a complete list in the wiki so I'll close this one.
