### ISSUE TITLE
Validate Client with BBDD instead of InMemory info

### ISSUE THREAD

**Issue by LORJIM** [spring-projects-experimental/spring-authorization-server#282]
Hi,

I'm not sure if this feature is already implemented on the project, but so far i didn't found anything about it.
Basically there is no "elegant" way of configuring a ClientDetailsService so we use the clients on the database instead of creating a InMemoryRegisteredClientRepository.

By my point of view, it should be something like in the previous versions of AuthorizationServer:

We have this on the AuthorizationServerConfig:

    @Override
    public void configure(ClientDetailsServiceConfigurer configurer) throws Exception {
        configurer.withClientDetails(couchbaseClientDetailsService);
    }

And then in the service we have:

@Service
public class CouchbaseClientDetailsService implements ClientDetailsService {
 
    @Autowired
    private CustomClientDetailsRepository customClientDetailsRepository;
 
    @Override
    public ClientDetails loadClientByClientId(String clientId) throws ClientRegistrationException {
 
        CustomClientDetails client = customClientDetailsRepository.findByClientId(clientId);
 
        String resourceIds = client.getResourceIds().stream().collect(Collectors.joining(","));
        String scopes = client.getScope().stream().collect(Collectors.joining(","));
        String grantTypes = client.getAuthorizedGrantTypes().stream().collect(Collectors.joining(","));
        String authorities = client.getAuthorities().stream().collect(Collectors.joining(","));
 
        BaseClientDetails base = new BaseClientDetails(client.getClientId(), resourceIds, scopes, grantTypes, authorities);
        base.setClientSecret(client.getClientSecret());
        base.setAccessTokenValiditySeconds(client.getAccessTokenValiditySeconds());
        base.setRefreshTokenValiditySeconds(client.getRefreshTokenValiditySeconds());
        base.setAdditionalInformation(client.getAdditionalInformation());
        base.setAutoApproveScopes(client.getScope());
        return base;
    }
}

It's behavior would be similar of what we're used to do on a UserDetailsService, but with client.

As i said before, i don't know if there's a way to do this already on the project, if it is, please tell me and i apologize.

Thank you for the hard work.

**Comment by jgrandja** [comment]
@LORJIM A JDBC implementation of `RegisteredClientRepository` is coming in the `0.1.2` release. See gh-265.

Closing as duplicate.

**Comment by jamesdube** [comment]
Is there a way to set additional information on the Registered client?
