### ISSUE TITLE
client_secret_post is supported but doesn't work.

### ISSUE THREAD

**Issue by gvermoen** [spring-projects-experimental/spring-authorization-server#286]
**Describe the bug**
According to http://auth-server:9000/.well-known/openid-configuration, both client_secret_basic and client_secret_post should be supported, however client_secret_post doesnt seem to work.
```
token_endpoint_auth_methods_supported: [
"client_secret_basic",
"client_secret_post"
],
```

**To Reproduce**
Run the sample authorization server. Execute the following:
```
curl -v -k --request POST \
  --url 'http://auth-server:9000/oauth2/token' \
  --header 'content-type: application/x-www-form-urlencoded;charset=UTF-8' \
  --data 'grant_type=client_credentials' \
  --data 'scope=message.read message.write' \
  --data 'client_id=messaging-client' \
  --data 'client_secret=secret'
```
The server responds with 401 {"error":"invalid_client"}

**Expected behavior**
I would expect to get a token response just like the client_secret_basic method which can be invoked as following:
```
curl --user messaging-client:secret -v -k --request POST \
  --url 'http://auth-server:9000/oauth2/token' \
  --header 'content-type: application/x-www-form-urlencoded;charset=UTF-8' \
  --data 'grant_type=client_credentials' \
  --data 'scope=message.read message.write'
```
In this case the server responds with 200 and {"access_token":"eyJraetcetcetcetcetc"}

**Sample**
The spring-authorization-server sample can be used to reproduce.
https://github.com/spring-projects-experimental/spring-authorization-server/tree/main/samples/boot/oauth2-integration/authorizationserver

**Comment by anoopgarlapati** [comment]
@gvermoen The `messaging-client` in the sample is configured only with `ClientAuthenticationMethod.BASIC` by default. You would need to edit the `AuthorizationServerConfig` and add `ClientAuthenticationMethod.POST` to the `messaging-client` registration.

**Comment by gvermoen** [comment]
Hi @anoopgarlapati you're absolutely correct! Thanks
