### ISSUE TITLE
Refresh token grant may issue ID token

### ISSUE THREAD

**Issue by anoopgarlapati** [spring-projects-experimental/spring-authorization-server#287]
As per [OpenID Connect Core 1.0 section 12.2](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse), `refresh_token` grant should issue ID token if the scope of the original request contains `openid`. 
The following requirements apply to the issued ID token in refresh token response:
- its `iss` Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
- its `sub` Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
- its `iat` Claim MUST represent the time that the new ID Token is issued,
- its `aud` Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,
- if the ID Token contains an `auth_time` Claim, its value MUST represent the time of the original authentication - not the time that the new ID token is issued,
- its `azp` Claim Value MUST be the same as in the ID Token issued when the original authentication occurred; if no `azp` Claim was present in the original ID Token, one MUST NOT be present in the new ID Token, and
- otherwise, the same rules apply as apply when issuing an ID Token at the time of the original authentication.

**Comment by jgrandja** [comment]
@anoopgarlapati Where in [Section 12.2. Successful Refresh Response](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse) does it state:

> refresh_token grant should issue ID token if the scope of the original request contains openid

I see:

> Upon successful validation of the Refresh Token, the response body is the Token Response of Section 3.1.3.3 except that **it might not contain an id_token**

which states that it might not contain the id_token, which implicitly means it's not required to be returned.

**Comment by anoopgarlapati** [comment]
@jgrandja Yes, it is not mandatory to return an ID token. However, the same section of the specification states 
> The following is a non-normative example of a Refresh Response:

`non-normative` indicating not a normal behavior to omit ID token for an OpenID Connect compliant provider.

I have checked the behavior in [Okta](https://developer.okta.com/docs/guides/refresh-tokens/use-refresh-token/) and [Auth0](https://auth0.com/learn/refresh-tokens/) and they issue an ID token in refresh token grant provided `openid` scope is present in the original authorization request.
