### ISSUE TITLE
Drop Java 8 compatibility

### ISSUE THREAD

**Issue by watsta** [spring-projects-experimental/spring-authorization-server#29]
Hi Everyone!

I understand that a big chunk of the Java community is still stuck on Java 8, but I wonder if there are any other reason why this project should still have compatibility to that version. As I understand it is not a supported version anymore and Java 11, the current LTS version has already been around for almost 2 years now. Wouldn't it be a good idea to default to Java 11 for this project?

**Comment by r331** [comment]
The main reason is 80% developers are using java 8)

**Comment by rwinch** [comment]
While I understand the appeal, we want to ensure we follow Spring conventions here. Not following the conventions puts this project in a hard place if we want to merge the code into Spring Security at some point. Right now JDK 8 is the minimum JDK for every other Spring project and we should remain consistent.
