### ISSUE TITLE
Add support for localhost/loopback addresses as redirect URI for certain scenarios/Spring profiles

### ISSUE THREAD

**Issue by robbydf** [spring-projects-experimental/spring-authorization-server#294]
**Expected Behavior**
The acceptance of localhost/loopback address as a redirect URI should be configurable (yet still defaults to false).

**Current Behavior**
In `OAuth2AuthorizationEndpointFilter.isValidRedirectUri(String, RegisteredClient)`, localhost/loopback address will always return `false`.

**Context**
While the backend developers are not really affected here, the developers of the frontend SPA which use localhost as the redirect URI is unable to test the features currently in development. Ideally, this should be configurable but defaults to the most secure configuration.

Any workaround besides downgrading to 0.1.0 will also be nice.

**Comment by sjohnr** [comment]
Hi @robbydf. Unfortunately, it looks as though this functionality is quite intentional. Here is the comment in that particular section of code:

```java
		String requestedRedirectHost = requestedRedirect.getHost();
		if (requestedRedirectHost == null || requestedRedirectHost.equals("localhost")) {
			// As per https://tools.ietf.org/html/draft-ietf-oauth-v2-1-01#section-9.7.1
			// While redirect URIs using localhost (i.e.,
			// "http://localhost:{port}/{path}") function similarly to loopback IP
			// redirects described in Section 10.3.3, the use of "localhost" is NOT RECOMMENDED.
			return false;
		}
```

Any way you can use loopback IP or add an entry to your DNS host file for a domain you have set up with the provider?

**Comment by robbydf** [comment]
Hello @sjohnr. Thanks but correct me If I'm wrong. I think loopback addresses are also invalid:


        		if (!LOOPBACK_ADDRESS_PATTERN.matcher(requestedRedirectHost).matches()) {
        			// As per https://tools.ietf.org/html/draft-ietf-oauth-v2-1-01#section-9.7
        			// When comparing client redirect URIs against pre-registered URIs
        			// authorization servers MUST utilize exact string matching.
        			return registeredClient.getRedirectUris().contains(requestedRedirectUri);      
        		}


And for adding a DNS entry, I think making a whole team of front-end developers do that is a bit counter intuitive. My take is that this should be as friction-less as possible (if possible).

**Comment by sjohnr** [comment]
Hi @robbydf.  I re-read that [section of the spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-01#section-9.7.1) again just to be sure. I think it is actually allowed to use e.g. `127.0.0.1` in the redirect URI. Here's what it says:

>  Specifying a redirect URI with the loopback IP literal
    rather than "localhost" avoids inadvertently listening on network
    interfaces other than the loopback interface.  It is also less
   susceptible to client-side firewalls and misconfigured host name
   resolution on the user's device.

But I definitely see your point about friction. We can look into a configuration option. It is hard to say at this point when we might be able to get to it though. Any chance you might be interested in contributing something to make it configurable?

**Comment by robbydf** [comment]
Hello @sjohnr. I retried using `127.0.0.1` and yes, it works. Thanks for pointing that out. I'll be closing this issue.

Regarding contribution, I'll certainly look in to it. Thanks again.
