### ISSUE TITLE
OAuth2TokenEndpointFilter is empty, java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by vnobo** [spring-projects-experimental/spring-authorization-server#307]
**Describe the bug**
spring boot version 2.5.0

When my project OAuth2TokenEndpointFilter does not exist,.

will OAuth2AuthorizationServerConfigurer go to register OAuth2TokenIntrospectionEndpointFilter

java.lang.NullPointerException: null

this code:
`OAuth2TokenIntrospectionEndpointFilter tokenIntrospectionEndpointFilter =
				new OAuth2TokenIntrospectionEndpointFilter(
						authenticationManager,
						providerSettings.tokenIntrospectionEndpoint());
		builder.addFilterAfter(postProcess(tokenIntrospectionEndpointFilter), OAuth2TokenEndpointFilter.class);`

throw error exception at class  HttpSecurity:
`private HttpSecurity addFilterAtOffsetOf(Filter filter, int offset, Class<? extends Filter> registeredFilter) {
		int order = this.filterOrders.getOrder(registeredFilter) + offset;
		this.filters.add(new OrderedFilter(filter, order));
		return this;
	}`

this.filterOrders.getOrder(registeredFilter)  this  java.lang.NullPointerException: null error.

I am not sure if it is a BUG, I did not find the relevant instructions, if not tell me how to eliminate the error.thank you

**Comment by anoopgarlapati** [comment]
This is a regression in Spring Security 5.5. Please see [comment](https://github.com/spring-projects-experimental/spring-authorization-server/issues/305#issuecomment-847559263).

**Comment by jgrandja** [comment]
Thanks @anoopgarlapati for pointing this out. Closing as duplicate gh-305
