### ISSUE TITLE
Fatal NullPointerException while initializing application context

### ISSUE THREAD

**Issue by softwaresale** [spring-projects-experimental/spring-authorization-server#308]
**Describe the bug**
I got the following `NullPointerException` while trying to initialize my Authorization server:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authorizationServerSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/OAuth2AuthorizationServerConfiguration.class]: Bean instantiation via factory method failed;
nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.web.SecurityFilterChain]: Factory method 'authorizationServerSecurityFilterChain' threw exception; 
nested exception is java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.springframework.security.config.annotation.web.builders.FilterOrderRegistration.getOrder(java.lang.Class)" is null
```
Specifically, the error happened while trying to start the `ApplicationContext`.

**To Reproduce**
I followed [Baeldung's Spring OAuth Server tutorial](https://www.baeldung.com/spring-security-oauth-auth-server) verbatium. I ran the application via `gradle bootRun`.

Spring boot plugin version: 2.5.0
Spring oauth2 authorization server version: 0.1.1
Gradle version: 7.0.4

**Expected behavior**
I expected the application to start.

**Sample**
My sample is [here](https://github.com/softwaresale/auth-server). I copy and pasted from the tutorial I referenced above.

Let me know if I can help out with any additional information. I am also interested in contributing to this project, so let me know if I can be of any help fixing this bug. Thanks again!

**Comment by anoopgarlapati** [comment]
This is a regression in Spring Security 5.5. Please see [comment](https://github.com/spring-projects-experimental/spring-authorization-server/issues/307#issuecomment-849363782).

**Comment by jgrandja** [comment]
Closing as duplicate #307
