### ISSUE TITLE
Gradle build failed with 401 Unauthorized

### ISSUE THREAD

**Issue by khaelys** [spring-projects-experimental/spring-authorization-server#311]
**Describe the bug**
Gradle build failed with 401 Unauthorized

**To Reproduce**
Just run `gradlew build` from root. I am on windows and aligned to main.

Short error description:
Could not HEAD 'https://repo.spring.io/plugins-snapshot/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.pom'. Received status code 401 from server: Unauthorized

**Comment by sjohnr** [comment]
Hi @khaelys. Can you describe your setup a bit more? Do you have any credentials stored in a gradle.properties on your machine, or anything else that might be impacting the build?

**Comment by LinhVu1027** [comment]
Hi @sjohnr, I had the same issue 3 days ago. I didn't do anything special, just cloned this project and built it by `./gradlew`. Now, it turned into:
```
Could not HEAD 'https://repo.spring.io/plugins-snapshot/com/github/ben-manes/gradle-versions-plugin/0.25.0/gradle-versions-plugin-0.25.0.jar'. Received status code 401 from server: Unauthorized
```

**Comment by bschoenmaeckers** [comment]
I'm getting the same error when building current master without any changes.

**Comment by jgrandja** [comment]
@khaelys @LinhVu1027 @bschoenmaeckers I haven't seen any issues on my end and I had a colleague just try it out with no issues. I would imagine there would be a lot more users reporting the same issue if it was related to the current build setup.

I suspect that it might be related to your environment? Have you tried building in another environment?

**Comment by eiswind** [comment]
I saw the same issue on my site last week!

**Comment by jgrandja** [comment]
@eiswind There were some infrastructure changes last week/weekend so it might have just be an intermittent problem. Are you seeing issues this week?

**Comment by bschoenmaeckers** [comment]
Deleting the .gradle folder in my home directory fixed the problem.

**Comment by jgrandja** [comment]
Thanks @bschoenmaeckers.

I'm going to close this as I believe this is related to the infrastructure changes on our end that caused an intermittent problem and/or it's related to the user's environment.

**Comment by eiswind** [comment]
When I run today I get 
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.11.4.
     Required by:
         project : > org.springframework.boot:spring-boot-gradle-plugin:2.4.5 > org.springframework.boot:spring-boot-buildpack-platform:2.4.5
      > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.11.4.
         > Could not get resource 'https://repo.spring.io/plugins-snapshot/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.pom'.
            > Could not HEAD 'https://repo.spring.io/plugins-snapshot/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.pom'. Received status code 401 from server: Unauthorized
```

Only custom thing I can see at my side is a gitlabPrivateToken in gradle.properties

**Comment by jgrandja** [comment]
@eiswind Can you try the same thing that @bschoenmaeckers  did in this [comment](https://github.com/spring-projects-experimental/spring-authorization-server/issues/311#issuecomment-868490608)

**Comment by eiswind** [comment]
Thx. this helped!

**Comment by khaelys** [comment]
> Thanks @bschoenmaeckers.
> 
> I'm going to close this as I believe this is related to the infrastructure changes on our end that caused an intermittent problem and/or it's related to the user's environment.

You are right, I'll answer on this issue when I find a solution

**Comment by johnwonder** [comment]
this help me

**Comment by WLZZJR** [comment]
i also hava a same issue,
Could not GET 'https://repo.spring.io/plugins-release/org/apache/xerces/resolver/2.9.1/resolver-2.9.1.pom'. Received status code 401 from server:
