### ISSUE TITLE
Scopes encoded with application/x-www-form-urlencoded will not get parsed correctly

### ISSUE THREAD

**Issue by bschoenmaeckers** [spring-projects-experimental/spring-authorization-server#312]
When the scope parameter is encoded with application/x-www-form-urlencoded () the space delimiter will be encoded as a plus sign (+) instead of %20. Currently this will break the scope validation because it will not recognize the delimiter between different scopes. The authorization server should accept both encodings.

**Comment by sjohnr** [comment]
Hi @bschoenmaeckers, thanks for the report. Would you be interested in submitting a pull request to fix this issue?

**Comment by bschoenmaeckers** [comment]
I'm getting the same error when building current master without any changes.

**Comment by bschoenmaeckers** [comment]
Sorry, it was a problem on my side. The + sign on my side got escaped to %2B which will correctly decode to a + sign in the authorization filter. This is the correct behavior because only unescaped + signs should be decoded to spaces as is the case now, so closing I will close this issue. Thanks anyway!
