### ISSUE TITLE
Provide JDBC implementation of OAuth2AuthorizationConsentService

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#313]
We need to provide a JDBC implementation of `OAuth2AuthorizationConsentService` that may be used for production deployments.

Related gh-283 gh-304

**Comment by ovidiupopa91** [comment]
Hi @jgrandja . I can work on this one.

**Comment by jgrandja** [comment]
Thanks for all your help @ovidiupopa91 !

**Comment by ovidiupopa91** [comment]
hi @jgrandja . Let me know when you have something planned for the `0.2.0` release. Unfortunately for the `0.1.2` release I won't be able to help anymore as I will be off next week.

**Comment by jgrandja** [comment]
@ovidiupopa91 Please ping me when you return from your time off. Enjoy!

**Comment by ovidiupopa91** [comment]
Hi @jgrandja . I'm back from my PTO. Let me know when you have something that I can take a look at.

**Comment by jgrandja** [comment]
Hi @ovidiupopa91 . Let me get back to you this Friday after I release `0.1.2`. Hope you enjoyed your time off :)

**Comment by ovidiupopa91** [comment]
Hi @jgrandja, sure. Yes, it was a great. A well deserved break :)

**Comment by jgrandja** [comment]
Hi @ovidiupopa91, I'm on PTO all of next week. I'll plan `0.2.0` tasks when I return and will follow up with you then. Thanks.

**Comment by ovidiupopa91** [comment]
Enjoy your time off @jgrandja !

**Comment by jgrandja** [comment]
Hi @ovidiupopa91. The plan for `0.2.0` is mostly polish and technical debt tasks as we are preparing the release to be production-ready. New features are on hold until after `0.2.0` is out.

One task on the list is adding update support in `JdbcRegisteredClientRepository.save()`. It currently only supports insert. Would this be of interest?

We also need to implement the [Client Configuration Endpoint](https://openid.net/specs/openid-connect-registration-1_0.html#ClientConfigurationEndpoint) which could go into `0.2.1`. Let me know if you're interested in this one as well.

**Comment by ovidiupopa91** [comment]
Hi @jgrandja, welcome back. I am ok with both of them 👍

**Comment by jgrandja** [comment]
Great @ovidiupopa91. Can you log the issues and then I can assign to you.

**Comment by ovidiupopa91** [comment]
@jgrandja issues opened: [gh-355](https://github.com/spring-projects-experimental/spring-authorization-server/issues/355) and [gh-356](https://github.com/spring-projects-experimental/spring-authorization-server/issues/356)
