### ISSUE TITLE
spring-authorization-server 0.1.1 authorization code not working

### ISSUE THREAD

**Issue by manhnv94** [spring-projects-experimental/spring-authorization-server#316]
Hi team,

I'm using the sample spring-authorization-server 0.1.1...
I put that link "localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=read" to browser, its redirect to login page... then i use default username/password to login, but not return to authorization code,  it return error 500.

Please support me,

Thanks

**Comment by sjohnr** [comment]
Hi @manhnv94. Could you provide a bit more detail on your issue?

Are you typing that URL from the description directly into a browser? Or are you using an OAuth 2.0 client to initiate this request? Are you sending a state parameter? Can you describe your specific steps to reproduce?

**Comment by vrapalis** [comment]
i have the same problem i use keycloak, in keycloak you can set up external idp (authorization server), when i will redirect from keyclok to  authotization server login form, after submit the form i not redirected back to keycloak for some reason. The redirect_url specified in the request and also in the client registration.

**Comment by sjohnr** [comment]
@vrapalis Can you provide a minimal sample that reproduces the issue without keycloak? I don't seem to see this issue with the samples, as @manhnv94 is seeing, so more information would be needed.

**Comment by manhnv94** [comment]
@sjohnr sorry, its my bad, i fixed it

Thank you
