### ISSUE TITLE
Authorization server metadata endpoint does not take into account the context path

### ISSUE THREAD

**Issue by bschoenmaeckers** [spring-projects-experimental/spring-authorization-server#317]
When your run spring under a different context path using for example the property `server.servlet.context-path=/api`, the url in de metadata do not match the actual path anymore.

A current workaround would be to include the context path in the issuer setting of `ProviderSettings`. But I would like to see the metadata include the context path by itself when you set it using the above property.

**Comment by sjohnr** [comment]
Hi @bschoenmaeckers. Thanks for the report. Given that the workaround is quite easy, and you would typically be providing the `ProviderSettings#issuer` anyway, I've marked this as an enhancement request for now. Would you be interested in submitting a PR?

**Comment by bschoenmaeckers** [comment]
Hi! Thanks for your response. What would be a desirable solution, just adding the context path to the issuer and so fix all the other urls or leave the issuer as it and add the context path to the endpoint uris directly?

**Comment by jgrandja** [comment]
@bschoenmaeckers 

> just adding the context path to the issuer

This is the intended customization required by the application. As @sjohnr mentioned, you would simply configure `ProviderSettings#issuer()` by including the context path. You could simply lookup the Spring Boot property `server.servlet.context-path` and use that to configure the `issuer`.

I'm going to close this as this is the responsibility of the application to configure the `ProviderSettings#issuer()`.
