### ISSUE TITLE
OidcProviderConfigurationEndpointFilter: TokenSigning Algorithm is hardcoded as RSA and doesn't support ECC

### ISSUE THREAD

**Issue by rajagopalanvivek** [spring-projects-experimental/spring-authorization-server#323]
**Describe the bug**
org.springframework.security.oauth2.server.authorization.oidc.web.OidcProviderConfigurationEndpointFilter: TokenSigning Algorithm is hardcoded as RSA and doesn't support ECC
Line: 90
				.idTokenSigningAlgorithm(SignatureAlgorithm.RS256.getName())

**To Reproduce**
org.springframework.security.oauth2.server.authorization.oidc.web.OidcProviderConfigurationEndpointFilter: TokenSigning Algorithm is hardcoded as RSA and doesn't support ECC
Line: 90
				.idTokenSigningAlgorithm(SignatureAlgorithm.RS256.getName())

**Expected behavior**
It needs to be dynamic, and parameterized to be something like:
.idTokenSigningAlgorithm(sigAlgorithm.getName())
so that it can support any ECC curves like ES256/512 etc.

**Sample**

Existing:
		OidcProviderConfiguration providerConfiguration = OidcProviderConfiguration.builder()
				.issuer(this.providerSettings.issuer())
				.authorizationEndpoint(asUrl(this.providerSettings.issuer(), this.providerSettings.authorizationEndpoint()))
				.tokenEndpoint(asUrl(this.providerSettings.issuer(), this.providerSettings.tokenEndpoint()))
				.tokenEndpointAuthenticationMethod("client_secret_basic")	// TODO: Use ClientAuthenticationMethod.CLIENT_SECRET_BASIC in Spring Security 5.5.0
				.tokenEndpointAuthenticationMethod("client_secret_post")	// TODO: Use ClientAuthenticationMethod.CLIENT_SECRET_POST in Spring Security 5.5.0
				.jwkSetUrl(asUrl(this.providerSettings.issuer(), this.providerSettings.jwkSetEndpoint()))
				.responseType(OAuth2AuthorizationResponseType.CODE.getValue())
				.grantType(AuthorizationGrantType.AUTHORIZATION_CODE.getValue())
				.grantType(AuthorizationGrantType.CLIENT_CREDENTIALS.getValue())
				.grantType(AuthorizationGrantType.REFRESH_TOKEN.getValue())
				.subjectType("public")
				.idTokenSigningAlgorithm(SignatureAlgorithm.RS256.getName())
				.scope(OidcScopes.OPENID)
				.build();

Solution/Proposed:
		OidcProviderConfiguration providerConfiguration = OidcProviderConfiguration.builder()
				.issuer(this.providerSettings.issuer())
				.authorizationEndpoint(asUrl(this.providerSettings.issuer(), this.providerSettings.authorizationEndpoint()))
				.tokenEndpoint(asUrl(this.providerSettings.issuer(), this.providerSettings.tokenEndpoint()))
				.tokenEndpointAuthenticationMethod("client_secret_basic")
				.tokenEndpointAuthenticationMethod("client_secret_post")
				.jwkSetUrl(asUrl(this.providerSettings.issuer(), this.providerSettings.jwkSetEndpoint()))
				.responseType(OAuth2AuthorizationResponseType.CODE.getValue())
				.grantType(AuthorizationGrantType.AUTHORIZATION_CODE.getValue())
				.grantType(AuthorizationGrantType.CLIENT_CREDENTIALS.getValue())
				.grantType(AuthorizationGrantType.REFRESH_TOKEN.getValue())
				.subjectType("public")
				.idTokenSigningAlgorithm(sigAlgorithm.getName())
				.scope(OidcScopes.OPENID)
				.build();

I understand it is a community project, and may not be very active. But still opening a defect which can be looked into sometime.

**Comment by jgrandja** [comment]
@rajagopalanvivek

`OidcProviderConfiguration.idTokenSigningAlgorithm` defaults to `RS256` as this is the default algorithm as defined in OpenId Connect 1.0 spec in section [3.1.3.7.  ID Token Validation](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation):

> The alg value SHOULD be the default of RS256 or the algorithm sent by the Client in the id_token_signed_response_alg parameter during Registration.

However, you can customize the default algorithm `RS256` to `EC` using an [OAuth2TokenCustomizer](https://github.com/spring-projects-experimental/spring-authorization-server/blob/f3cb8f758ca999e2625526939af81ac18317187b/oauth2-authorization-server/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/authorization/OAuth2AuthorizationCodeGrantTests.java#L517) `@Bean` and customizing it with `context.getHeaders().jwsAlgorithm(SignatureAlgorithm.ES256)`. You also need to ensure the `JWKSource<SecurityContext>` `@Bean` contains the EC Key.

I'm going to close this signing the ID Token with an EC Key is possible.

**Comment by rajagopalanvivek** [comment]
@jgrandja
Thank you. I am also aware that it can be customized in many ways, which I did already for many samples.
ECC has been into the market for sometime, and it might replace RSA completely after few years. Hence, it is high time to support them as defaults rather than hardcoding.
As "spring-authorization-server project" is something vey new and is experimental, having default support for both algorithms by default is something which is more adequate.
We all know old *-oauth2 project had the same problem that it was highly hardcoding algorithm as RSA along with token converters. But, anyway, it is deprecated now.

**Comment by rajagopalanvivek** [comment]
@jgrandja 
One more question: As it's an experimental project.

I understand that the default support for this project would be JWKS and JWS.
We can customize it for JWS+JWE also in some way.

Do you see any future plans for more support on JWE?
