### ISSUE TITLE
OAuth2AuthorizationCodeAuthenticationProvider does not properly deserialize OAuth2Authorization object attributes

### ISSUE THREAD

**Issue by ddubson** [spring-projects-experimental/spring-authorization-server#324]
**Describe the bug**

When using the JDBC implementation for `OAuth2AuthorizationService`, the `OAuth2AuthorizationCodeAuthenticationProvider` is not able to properly deserialize the stored attributes within `OAuth2Authorization` object upon authentication. Specifically, the attributes within OAuth2Authorization object are stored as `LinkedHashMap`s, and when it comes time for `OAuth2AuthorizationCodeAuthenticationProvider.authenticate` method to use the attributes, a `ClassCastException` is thrown due to the fact that a LinkedHashMap is not castable to a specific object, such as an `OAuth2AuthorizationRequest` (one of the attributes). All attributes suffer from this casting issue.

**To Reproduce**

- Enable JDBC implementation of at least `OAuth2AuthorizationService`. Ideally, all services should be JDBC-based. 
- Set up H2 In-memory database, and load schema as defined in `src/main/resources`.
- Launch the authorization server, sample client, and sample resource server
- Navigate to sample client (http://localhost:8080)
- Get redirected to auth server, sign in with `user1`/`password`, you will be redirected back.
- Observe error: `too many redirects` in browser. `ClassCastException` on server console.

Should be similar to the following:

```java
java.lang.ClassCastException: java.util.LinkedHashMap incompatible with org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest
	at org.springframework.security.oauth2.server.authorization.authentication.OAuth2AuthorizationCodeAuthenticationProvider.authenticate(OAuth2AuthorizationCodeAuthenticationProvider.java:121) ~[main/:na]
```

**Expected behavior**

- Enable JDBC implementation of at least `OAuth2AuthorizationService`. Ideally, all services should be JDBC-based.
- Launch the authorization server, sample client, and sample resource server
- Navigate to sample client
- Get redirected to auth server, sign in with `user1`/`password`, you will be redirected back.
- Observe resources fetched from resource server (no errors)

**Sample**

[Commit that replicates the bug](https://github.com/pivotal/spring-authorization-server/commit/137da46cd02840f3cc504fdb7464224951c56748)

**Comment by jgrandja** [comment]
Thanks for the report @ddubson. We discovered the bug as well and are currently working on a fix.

**Comment by harrycjy1** [comment]
im facing the same issue with custom implementation of OAuth2AuthorizationService with mongodb with 0.4.0 version is there any way to fix this??
