### ISSUE TITLE
Attributes column of the authorization table is to small

### ISSUE THREAD

**Issue by bschoenmaeckers** [spring-projects-experimental/spring-authorization-server#328]
The attributes column defined [here](https://github.com/spring-projects-experimental/spring-authorization-server/blob/473dedb9addae1c8f048df8333b7c08a16f49996/oauth2-authorization-server/src/main/resources/org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql#L6) is to small. It is now only 1000 chars long but on my setup it surpasses that (roughly 1100-1200 chars).  You should expand the varchar or consider another type.

**Comment by sjohnr** [comment]
Thanks for the report @bschoenmaeckers. I ran into the same. I'll be including a fix for this along with the fix for gh-324 as I'll be expanding the number of characters used even further.
