### ISSUE TITLE
Settings in RegisteredClient are not json serializable with Jackson

### ISSUE THREAD

**Issue by bschoenmaeckers** [spring-projects-experimental/spring-authorization-server#330]
ClientSettings and TokenSettings are not serializable with the BeanSerializer because they do not have getter methods prefixed with "get". This prevents me from serializing a RegisteredClient to json in a custom RestController.

**Comment by bschoenmaeckers** [comment]
I can submit a PR for a jackson module that can serialize all the Settings classes if you want me to.

**Comment by sjohnr** [comment]
@bschoenmaeckers I just merged gh-331 which includes a start for the Jackson module. I think you could go ahead and get a head start on `ClientSettings` and `TokenSettings`, as well as `RegisteredClient`, and add them to that module. However, I don't think we will be able to include this in the next release. We can potentially look at including it in 0.2.0.

**Comment by sjohnr** [comment]
Just another note on this: while I think you could get started creating the mixin (since you need it for yourself), it may not be needed in the framework right now. We may need to wait and see if it shows up as a need before we would want to look at it.

**Comment by sjohnr** [comment]
@bschoenmaeckers, while this suggestion would be nice to have, this is not an immediate need in the framework itself (that I'm aware of). I'm going to close this for now. I will keep an eye on whether this pops up as a need, and reopen if that is the case.
