### ISSUE TITLE
I can not get token using client_credentials

### ISSUE THREAD

**Issue by nguyentriloi** [spring-projects-experimental/spring-authorization-server#336]
`@Bean
  public RegisteredClientRepository registeredClientRepository() {
    RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
        .clientId("client")
        .clientSecret("secret")
        .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
        .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
        .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
        .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
        .redirectUri("http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc")
        .redirectUri("http://127.0.0.1:8080/authorized")
        .scope(OidcScopes.OPENID)
        .scope("message.read")
        .scope("message.write")
        .clientSettings(clientSettings -> clientSettings.requireUserConsent(true))
        .build();
    return new InMemoryRegisteredClientRepository(registeredClient);
  }`

This is my test in postman
![Screenshot from 2021-07-02 00-04-57](https://user-images.githubusercontent.com/39092516/124162892-3062e000-dac9-11eb-9258-5df9cc47813b.png)

pls help me get token use grant_type  = client_credentials

**Comment by sjohnr** [comment]
@nguyentriloi, thanks for reaching out. This question is better suited for [stackoverflow](http://stackoverflow.com/questions/tagged/spring-security) with the spring-security tag. We prefer to use GitHub for enhancements and bug reports.
