### ISSUE TITLE
RegisteredClient should be an interface like ClientDetails in the old Oauth library

### ISSUE THREAD

**Issue by ghartz-hz** [spring-projects-experimental/spring-authorization-server#339]
**Expected Behavior**
The original deprecated OAuth library used an interface for representing registered clients, which enabled better integration stories with existing systems, including the use of Spring Data repositories to back the client storage (for consistent auditing, etc).  Spring Authorization Server is using a concrete type to represent clients, which locks implementers into using the pre-built repositories, or at least repository implementations that do not require modifications of the entity in question, or having to do hacky copy-on-read/copy-on-write patterns.

**Current Behavior**
The system is using a concrete type throughout the APIs to represent a client

**Context**

In our particular use case, we were blocked on attempting to migrate from the deprecated library to the new one because our client registry exists in a sharded database that needs a tenant identifier -- which is present in our JPA entity representing a client, but we can't reuse that entity with this library.

We're still in an evaluation phase to determine if we fork and continue enhancing the legacy library, if we convert to this library, or DIY an implementation against Nimbus directly. It'd help to understand if this change was an oversight or a deliberate architectural change.

**Comment by sjohnr** [comment]
@ghartz-hz, thanks for your interest in the project.

Currently, the framework creates a `RegisteredClient` (not marked as `final`) in two places:
* [JdbcRegisteredClientRepository.java#L193](https://github.com/spring-projects-experimental/spring-authorization-server/blob/41dd68903c5b3401009253712f3a581024234668/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/client/JdbcRegisteredClientRepository.java#L193)
* [OidcClientRegistrationAuthenticationProvider.java#L182](https://github.com/spring-projects-experimental/spring-authorization-server/blob/41dd68903c5b3401009253712f3a581024234668/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/OidcClientRegistrationAuthenticationProvider.java#L182) (only used for OpenID client registration)

Both of these locations should be fairly easy to plug in custom code to create your own extension, if you're even using either of these components. Normally however, you would be providing your own instances of `RegisteredClient` through your own implementation of `RegisteredClientRepository` and/or `AuthenticationProvider`.

I'm going to close this for now, as I don't believe the lack of an interface for `RegisteredClient` prevents your use case in any way. If I've missed something, please feel free to reopen. Also, if you have questions about how to implement such a use case, feel free to open a [stackoverflow question](https://stackoverflow.com/questions/tagged/spring-security) and link to it here, and I'll take a look.

**Comment by ghartz-hz** [comment]
The problem with RegisteredClient being a concrete type (even if not final) is that essentially every method in it ends up having to be overridden to add annotations to them, if your persistence engine needs annotations (like Spring Data JPA).  Its a sloppy and fragile solution, because there's no contract to guarantee that functional changes aren't made to the underlying class. 

There's no reason a concrete default implementation of an interface, with the pre-existing builder pattern, etc, shouldn't be there, but it's just a strange architectural decision. Particularly given that its not consistent with how the rest of Spring works (everything has interfaces, and default implementations) and lends this library to not actually integrating well with the rest of Spring. (The repository is sort of like, but not, a Spring Data repository, its configured very differently, etc...)

It feels like a "spring adjacent" project, not really a first class component within Spring Security.

**Comment by ghartz-hz** [comment]
Just to clarify, what I mean (as an example) is the library adding a new field to RegisteredClient in the future -- and because there's an implementation of it in the superclass, a subclass of it won't produce a compiler error, and data may not get persisted, audited, or some other similar bug, whereas the interface change would cause a compiler error.
