### ISSUE TITLE
Support for OAuth 2.0 Device Authorization Grant

### ISSUE THREAD

**Issue by pkostrzewa** [spring-projects-experimental/spring-authorization-server#34]
This epic should group all issues that will deliver support for Device Authorization Grant as per [RFC8628](https://tools.ietf.org/html/rfc8628).

**Comment by jgrandja** [comment]
Thanks for logging this @pkostrzewa.

At the moment, this will likely be on the lower priority list as we need to focus on implementing the more widely used OAuth 2.0 flows.

I'm curious, are you aware of any provider that has implemented this new grant type?

FYI, I'm in the process of putting together a roadmap that will prioritize the features to be developed. I will log an issue this week that provides a link to the roadmap along with the first set of epics and associated issues.

**Comment by jgrandja** [comment]
@pkostrzewa I couldn't find a way to convert this issue to an epic so I'll close this in favour of #44.
