### ISSUE TITLE
When will the password mode be launched?

### ISSUE THREAD

**Issue by q2587218416** [spring-projects-experimental/spring-authorization-server#349]
When will the password mode be launched?

**Comment by sjohnr** [comment]
@q2587218416, we will not be providing support for the `password` grant as it is deprecated in OAuth 2.1. See [this comment](https://github.com/spring-projects-experimental/spring-authorization-server/pull/115#issuecomment-696009503).

I'm going to close this issue. If you have questions about how to support the `password` grant or other questions related to this project, feel free to use [stackoverflow](https://stackoverflow.com/questions/tagged/spring-security) to ask the community.
