### ISSUE TITLE
When will it be stable to be used in commercial production environment?

### ISSUE THREAD

**Issue by fzyzcjy** [spring-projects-experimental/spring-authorization-server#35]
Hi thanks for the newly rewritten spring security & spring auth server! I wonder when will it be stable to be used in commercial production environment?

In other words, if I need to use an OAuth solution in about 3 months (say, July), then which do you suggest:

1. The deprecated Spring Security Oauth
2. The new Spring Security, with 3rd party like Keycloak
3. The new Spring Security, with this repo (stable?)

Thanks very much!

**Comment by jgrandja** [comment]
@fzyzcjy This project was just initiated so we are far off from a 1.0.0 release. I'm putting together a roadmap this week and setting up the initial set of tasks. You can track the roadmap to see when features are implemented and released. I'll be logging an issue with a link to the roadmap this week.

**Comment by fzyzcjy** [comment]
@jgrandja Thanks very much! So which way do you suggest: The deprecated Spring Security Oauth, since it is very mature; or the new Spring Security, with 3rd party like Keycloak?

**Comment by jgrandja** [comment]
I would recommend the client and resource server support in Spring Security 5.x. As far as Authorization Server support goes, you'll have to make that decision yourself based on your requirements. I will say that Spring Security OAuth will be supported until at least May 2021, but we may support it further depending on the progress of this project and where things are at.

**Comment by fzyzcjy** [comment]
Thanks very much!
