### ISSUE TITLE
Upgrade version 0.1.2, login appears / error type = none, status = 999

### ISSUE THREAD

**Issue by heanbian** [spring-projects-experimental/spring-authorization-server#351]
Upgrade version 0.1.2, login appears / error type = none, status = 999
eg:  spring boot version 2.5.2

**Comment by sjohnr** [comment]
Hi @heanbian, thanks for the report. Can you please provide more details on your issue. Can you provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by heanbian** [comment]
Replace "ClientAuthenticationMethod.BASIC" with "ClientAuthenticationMethod.CLIENT_SECRET_BASIC"

**Comment by jgrandja** [comment]
Thanks @heanbian. This is one of the cleanup tasks that I have on my list for `0.2.0` release.
