### ISSUE TITLE
Epic: Authorization Request Exchange

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#36]
This epic will track the progress of the following feature:

Provide an implementation of the Authorization Request/Response (Exchange) for the `authorization_code` grant.

This epic is divided into multiple issues, in order to support parallel work streams.

#66 Implement Authorization Endpoint

See the ZenHub [project board](https://app.zenhub.com/workspaces/authorization-server-5e8f3182b5e8f5841bfc4902/board?repos=248032165).

**Comment by paurav-munshi** [comment]
@jgrandja I am assuming we are still waiting for the Roadmap. Let me know when its good to pick up this issue. I wish to work on this issue. 

Also is this connected with #41 ? I am asking this since this end point will generate the authorization code using the authorization code service.

**Comment by dfcoffin** [comment]
@paurav-munshi It appears @jgrandja is reorganizing the Issues into EPIC entries, which will then have individual issues attached to them.  The Roadmap can then be easily mapped to EPIC entries to be prioritized and managed.

**Comment by jgrandja** [comment]
@paurav-munshi Yes @dfcoffin is spot on. I'm in the process of laying out the work for implementing `authorization_code` grant. I'm targeting by end of this week (maybe earlier) to have things setup and ready to go. I'll reach out to you when we are organized on our end.
