### ISSUE TITLE
ClientSecretBasicAuthenticationConverter method convert error return  

### ISSUE THREAD

**Issue by TianLiangZhou** [spring-projects-experimental/spring-authorization-server#372]
```java
return new OAuth2ClientAuthenticationToken(clientID, clientSecret, ClientAuthenticationMethod.BASIC, extractAdditionalParameters(request));
```

Parameter 3 should not be `ClientAuthenticationMethod.BASIC`, it should be `ClientAuthenticationMethod.CLIENT_SECRET_BASIC`

**Comment by jgrandja** [comment]
@TianLiangZhou It was updated recently and is now [ClientAuthenticationMethod.CLIENT_SECRET_BASIC](https://github.com/spring-projects-experimental/spring-authorization-server/blob/5593208e616ab2977809c21ef74421e0966e8727/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/authentication/ClientSecretBasicAuthenticationConverter.java#L92).
