### ISSUE TITLE
IllegalStateException when using WebSecurityConfigurerAdapter 

### ISSUE THREAD

**Issue by oridool** [spring-projects-experimental/spring-authorization-server#383]
**Describe the bug**
I'm not sure it is a bug, or maybe I'm doing something wrong.
I'm building an application that is both utilizing the authorization server, but also contains additional REST controller. 
In that manner, I guess my app plays both the role of authorization server and resource server.

I've just upgraded to latest code of spring-authorization-server, it used to work for me in the past.
But now, I get the following exception when app starts:

`java.lang.IllegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.`

**To Reproduce**
I took the configuration from the sample:

```java
	@Bean
	@Order(Ordered.HIGHEST_PRECEDENCE)
	public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
		OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);
		return http.formLogin(Customizer.withDefaults()).build();
	}
```

And also added my REST endpoints configuration, in which I use my own jwt converter:
```java
@Configuration
@Order(200)
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true, jsr250Enabled = true)
public class AuthenticationConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    @Qualifier("resourceServerJwtConverter")
    JwtAuthenticationConverter jwtAuthenticationConverter;

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .antMatchers("/actuator/health").permitAll()
                .antMatchers("/actuator/health/readiness").permitAll()
                .antMatchers("/actuator/health/liveness").permitAll()
                .antMatchers("/actuator/prometheus").permitAll()
                .anyRequest().authenticated().and()
                .oauth2ResourceServer().jwt().jwtAuthenticationConverter(jwtAuthenticationConverter);
    }
}

```

**Expected behavior**
In the past, using `@Order` helped and I was able to have both configurations (before adding the SecurityFilterChain bean).

I'd like to be able to configure my REST endpoints security, as a resource server, and also use the authentication server in the same application.

I tried also to remove the SecurityFilterChain bean, and configure everything as WebSecurityConfigurerAdapter, but without any success. I was able to call the `/token` endpoint, but it seems that my REST endpoint is not protected by spring security at all and can be called without any token in the header.
Here is my trial:

```java
    @Override
    public void configure(HttpSecurity http) throws Exception {

        OAuth2AuthorizationServerConfigurer<HttpSecurity> authorizationServerConfigurer =
                new OAuth2AuthorizationServerConfigurer<>();
        RequestMatcher endpointsMatcher = authorizationServerConfigurer
                .getEndpointsMatcher();
        http
                .requestMatcher(endpointsMatcher)
                .authorizeRequests(authorizeRequests -> {
                            try {
                                authorizeRequests
                                        .antMatchers("/actuator/health").permitAll()
                                        .antMatchers("/actuator/health/readiness").permitAll()
                                        .antMatchers("/actuator/health/liveness").permitAll()
                                        .antMatchers("/actuator/prometheus").permitAll()
                                        .anyRequest().authenticated().and()
                                        .oauth2ResourceServer().jwt().jwtAuthenticationConverter(jwtAuthenticationConverter);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                )
                .csrf(csrf -> csrf.ignoringRequestMatchers(endpointsMatcher))
                //.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt)
                .apply(authorizationServerConfigurer);
    }
```

Is there a way to do that?
@jgrandja - can you advise on that?

Thanks!

**Comment by edwardzjl** [comment]
> I've just upgraded to latest code of spring-authorization-server, it used to work for me in the past.
> But now, I get the following exception when app starts:
> 
> `java.lang.IllegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.`
> 

Spring Security 5.4 adds support for publishing a SecurityFilterChain bean; but there is no clear way to order SecurityFilterChain beans and WebSecurityConfigurerAdapter beans. So you need to pick one or the other.

> I tried also to remove the SecurityFilterChain bean, and configure everything as WebSecurityConfigurerAdapter, but without any success. I was able to call the `/token` endpoint, but it seems that my REST endpoint is not protected by spring security at all and can be called without any token in the header.
> Here is my trial:
> 
> ```java
>     @Override
>     public void configure(HttpSecurity http) throws Exception {
> 
>         OAuth2AuthorizationServerConfigurer<HttpSecurity> authorizationServerConfigurer =
>                 new OAuth2AuthorizationServerConfigurer<>();
>         RequestMatcher endpointsMatcher = authorizationServerConfigurer
>                 .getEndpointsMatcher();
>         http
>                 .requestMatcher(endpointsMatcher)
>                 .authorizeRequests(authorizeRequests -> {
>                             try {
>                                 authorizeRequests
>                                         .antMatchers("/actuator/health").permitAll()
>                                         .antMatchers("/actuator/health/readiness").permitAll()
>                                         .antMatchers("/actuator/health/liveness").permitAll()
>                                         .antMatchers("/actuator/prometheus").permitAll()
>                                         .anyRequest().authenticated().and()
>                                         .oauth2ResourceServer().jwt().jwtAuthenticationConverter(jwtAuthenticationConverter);
>                             } catch (Exception e) {
>                                 e.printStackTrace();
>                             }
>                         }
>                 )
>                 .csrf(csrf -> csrf.ignoringRequestMatchers(endpointsMatcher))
>                 //.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt)
>                 .apply(authorizationServerConfigurer);
>     }
> ```

The problem is, you are configuring your REST endpoints inside an auth-server endpoint matcher. 
(the `requestMatcher(endpointsMatcher)` line)

In order to achieve your goal, you can define multiple WebSecurityConfigurerAdapter, one for authorization server endpoints, and one for your own REST endpoints, and assign them different Order, just like you did in the past.

Or you can try the SecurityFilterChain bean way, with multiple beans and different Order too, which I think is more clear.

For example:

```java

// auth server filter
@Bean
@Order(Ordered.HIGHEST_PRECEDENCE)
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
        OAuth2AuthorizationServerConfigurer<HttpSecurity> authorizationServerConfigurer =
                new OAuth2AuthorizationServerConfigurer<>();
        RequestMatcher endpointsMatcher = authorizationServerConfigurer
                .getEndpointsMatcher();
	http
		.requestMatcher(endpointsMatcher )
		.authorizeRequests(authorizeRequests -> authorizeRequests
				.anyRequest().authenticated()
		)
		// add any config you need
		.apply(authorizationServerConfigurer);
}

// your REST endpoints filter
@Bean
@Order(1) // another order
public SecurityFilterChain authorizationServerSecurityFilterChain(HttpSecurity http) throws Exception {
        RequestMatcher yourEndpointsMatcher;
	http
		.requestMatcher(yourEndpointsMatcher)
		.authorizeRequests(authorizeRequests -> {
				try {
					authorizeRequests
						.antMatchers("/actuator/health").permitAll()
						.antMatchers("/actuator/health/readiness").permitAll()
						.antMatchers("/actuator/health/liveness").permitAll()
						.antMatchers("/actuator/prometheus").permitAll()
						.anyRequest().authenticated().and()
						.oauth2ResourceServer().jwt().jwtAuthenticationConverter(jwtAuthenticationConverter);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		)
		.csrf(csrf -> csrf.ignoringRequestMatchers(endpointsMatcher))
		//.oauth2ResourceServer(OAuth2ResourceServerConfigurer::jwt)
		.apply(authorizationServerConfigurer);
}

```

**Comment by oridool** [comment]
@edwardzjl ,
Thank you very much for the detailed explanation!
I was able to configure spring security in both ways you mentioned and it works well for me.

Issue can be closed :)

**Comment by ShannonHung** [comment]
i am curious how to configure AuthenticationManagerBuilder without extends WebSecurityConfigurerAdapter
```
@Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.userDetailsService(userDetailService)
                .passwordEncoder(new BCryptPasswordEncoder());
    }
```

**Comment by edwardzjl** [comment]
> i am curious how to configure AuthenticationManagerBuilder without extends WebSecurityConfigurerAdapter. I am facing the same question about IllegalStateException when using WebSecurityConfigurerAdapter. Because I want to use my own UserDetailsService. But i have no idea to set the userDetailsService by SecurityFilterChain.
> 
> ```
> @Override
>     protected void configure(AuthenticationManagerBuilder auth) throws Exception {
>         auth.userDetailsService(userDetailService)
>                 .passwordEncoder(new BCryptPasswordEncoder());
>     }
> ```

In my project I can config `AuthenticationManagerBuider` without extending `WebSecurityConfigurerAdapter` like this:

```java
@Autowired
void configProviders(AuthenticationManagerBuilder authenticationManagerBuilder) {
    authenticationManagerBuilder
            .authenticationProvider(someProvider)
            .authenticationProvider(anotherProvider);
}
```

But I'm not sure whether it's the recommended way to do that.

**Comment by ledengesd** [comment]
@oridool Hi Ori, I'm facing a similar issue. I couldn't get my authorization server working with WebSecurityConfigurer. Do you mind sharing your WebSecurityConfigurer details for Authorization Server? Thanks and appreciate it.

**Comment by lutics** [comment]
@ledengesd 

```
@EnableWebSecurity
class SecurityConfig {

    @Configuration
    @Order(Ordered.HIGHEST_PRECEDENCE)
    class AuthorizationServerWebSecurityConfig : WebSecurityConfigurerAdapter() {

        override fun configure(http: HttpSecurity) {
            OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http)
        }
    }

    @Configuration
    @Order(1)
    class DefaultSecurityConfig(
        private val authenticationProvider: SampleAuthenticationProvider,
        private val successHandler: AuthenticationSuccessHandler,
        private val failureHandler: AuthenticationFailureHandler
    ) : WebSecurityConfigurerAdapter() {

        override fun configure(http: HttpSecurity) {
            http.authorizeRequests().anyRequest().permitAll()

            http.csrf().disable()
            http.cors().disable()

            http.formLogin()
                .successHandler(successHandler)
                .failureHandler(failureHandler)
        }

        override fun configure(auth: AuthenticationManagerBuilder) {
            auth.authenticationProvider(authenticationProvider)
        }
    }
}
```

**Comment by oridool** [comment]
> @oridool Hi Ori, I'm facing a similar issue. I couldn't get my authorization server working with WebSecurityConfigurer. Do you mind sharing your WebSecurityConfigurer details for Authorization Server? Thanks and appreciate it.
> 
> The specific issue I'm having is that the two config classes extending WebSecurityConfigurerAdapter will have separate session context, meaning I have to login twice for accessing the endpoints protected by each WebSecurityConfigurerAdapter. Is there a way to unify two WebSecurityConfigurer to use just one security context?

@ledengesd , I'm not sure how to answer your last question regarding multiple login. In my application, I just added another REST endpoint and set it in WebSecurityConfigurer. It is assumed the user already logged in with an IDP and the REST request already contains the JWT. 
I simply followed the example provided by @edwardzjl  .
The point is that you have to choose between the 2 methods and you cannot mix `SecurityFilterChain` with `WebSecurityConfigurer`.

Here is a snapshot of my current code, I hope it would help you:

```java

@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true, jsr250Enabled = true)
public class AuthenticationConfig {

    @Configuration
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public static class AuthenticationConfigAuthz extends WebSecurityConfigurerAdapter {

        @Override
        public void configure(HttpSecurity http) throws Exception {
            OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);
        }
    }

    @Configuration
    @Order(200)
    public static class AuthenticationConfigJwt extends WebSecurityConfigurerAdapter {

        @Autowired
        @Qualifier("resourceServerJwtConverter")
        JwtAuthenticationConverter jwtAuthenticationConverter;

        @Override
        public void configure(HttpSecurity http) throws Exception {
            ExpressionUrlAuthorizationConfigurer<HttpSecurity>.ExpressionInterceptUrlRegistry expressionInterceptUrlRegistry =
                    http.csrf().disable()
                            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
                            .authorizeRequests();


            expressionInterceptUrlRegistry
                    .antMatchers("/actuator/health").permitAll()
                    .antMatchers("/actuator/health/readiness").permitAll()
                    .antMatchers("/actuator/health/liveness").permitAll()
                    .antMatchers("/actuator/info").permitAll()
                    .antMatchers("/actuator/prometheus").permitAll()
                    .anyRequest().authenticated().and()
                    .oauth2ResourceServer().jwt().jwtAuthenticationConverter(jwtAuthenticationConverter);
            // refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
            http.headers()
                    .contentSecurityPolicy("script-src 'self' ; object-src 'self'; ");

        }
    }
}
```

**Comment by hezhongfeng** [comment]
@oridool Thanks for your code, it works well.

**Comment by ShannonHung** [comment]
> > i am curious how to configure AuthenticationManagerBuilder without extends WebSecurityConfigurerAdapter. I am facing the same question about IllegalStateException when using WebSecurityConfigurerAdapter. Because I want to use my own UserDetailsService. But i have no idea to set the userDetailsService by SecurityFilterChain.
> > ```
> > @Override
> >     protected void configure(AuthenticationManagerBuilder auth) throws Exception {
> >         auth.userDetailsService(userDetailService)
> >                 .passwordEncoder(new BCryptPasswordEncoder());
> >     }
> > ```
> 
> In my project I can config `AuthenticationManagerBuider` without extending `WebSecurityConfigurerAdapter` like this:
> 
> ```java
> @Autowired
> void configProviders(AuthenticationManagerBuilder authenticationManagerBuilder) {
>     authenticationManagerBuilder
>             .authenticationProvider(someProvider)
>             .authenticationProvider(anotherProvider);
> }
> ```
> 
> But I'm not sure whether it's the recommended way to do that.

Thank you! It works. 
This is my current SecurityConfig

```java
//enable security debugging which will log detailed security information on each request.
//This way, when we send a request to the server, all the request information will be logged.
@EnableWebSecurity(debug = true)
public class SecurityConfig {

    @Autowired
    UserDetailService userDetailService;

    @Autowired
    void configProviders(AuthenticationManagerBuilder authenticationManagerBuilder) throws Exception {
        authenticationManagerBuilder
                .userDetailsService(userDetailService)
                .passwordEncoder(new BCryptPasswordEncoder());
    }


    // @formatter:off
    @Bean
    SecurityFilterChain defaultSecurityFilterChain(HttpSecurity http) throws Exception {
        http
                .authorizeRequests(authorizeRequests ->
                        authorizeRequests.anyRequest().authenticated()
                )
                .formLogin(withDefaults());
        return http.build();
    }

}
```

**Comment by shanzhaozhen** [comment]
I want to change session to stateless . Can this be achieved?

**Comment by edwardzjl** [comment]
> I want to change session to stateless . Can this be achieved?

I believe what you want is a spring-security feature which is not related to this issue.
