### ISSUE TITLE
The JDBC-based sample code does not work properly

### ISSUE THREAD

**Issue by CaptainStevenRogers-ZZP** [spring-projects-experimental/spring-authorization-server#385]
**Describe the bug**
When I run `'authorizationServer'`, `'resourceserver'` and `'client'` in the sample code, I found that I still jump back to the login page even after I log in with the correct account and password. But when I run the `'authorizationserver-custom-consent-page'`, the authorization process works correctly.

**Comment by mikee** [comment]
I can replicate - swapping to the InMemoryRegisteredClientRepository to match the custom consent sample seems to fix it for me, so possibly an issue with the JDBC version

**Comment by jgrandja** [comment]
Thanks for the report @CaptainStevenRogers-ZZP.

This is now fixed via ea7c689
