### ISSUE TITLE
Use the mobile phone number and verification code to log in

### ISSUE THREAD

**Issue by robintian-bud** [spring-projects-experimental/spring-authorization-server#386]
**Expected Behavior**

  It is hoped that mobile phone number and verification code can be used for login in the future
**Current Behavior**

Most websites in China support the system login by using the mobile phone number and the verification code sent by the service provider. I hope it can be supported in the native framework. Before this, we need to extend the original framework in the development process to support it
**Context**

**Comment by luyanfeng** [comment]
之前用老项目扩展了下手机验证码登录，真的是好啰嗦啊。希望可以直接提供下。

**Comment by edwardzjl** [comment]
This project aims to provide oauth support, basic authentication workflow is out of the project's scope.

You should open this issue to [spring security](https://github.com/spring-projects/spring-security)

**Comment by vrapalis** [comment]
I am not expert of this project, but in spring you can customize many things, here you need custom login form and custom filter and authentication provider?

**Comment by jgrandja** [comment]
Thanks for the suggestion @robintian-bud. However, @edwardzjl is correct, this project strictly focuses on OAuth and OpenID Connect support only.

Please see the following for further information:

- [spring-security#2603](https://github.com/spring-projects/spring-security/issues/2603)
- [spring-security#6842](https://github.com/spring-projects/spring-security/pull/6842)
- [spring-security-samples#7](https://github.com/spring-projects/spring-security-samples/issues/7)

**Comment by robintian-bud** [comment]
@jgrandja @edwardzjl  thanks a lot
