### ISSUE TITLE
Implement Client Authentication

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#39]
The client must authenticate when calling the authorization server's token endpoint.

The `OAuth2ClientAuthenticationFilter` should be implemented as a `Filter`. The initial implementation should support HTTP Basic only.

### Implementation Requirements

- the `Filter` should process requests for the (default) path `/oauth2/token` and if HTTP Basic credentials are available in the request
- the `OAuth2ClientAuthenticationToken` should be passed to the `AuthenticationManager`
- the `AuthenticationManager` should be composed of `OAuth2ClientAuthenticationProvider` (in a later story)
- the `OAuth2ClientAuthenticationProvider` should use the `RegisteredClientRepository` #40 to look up and validate the client credentials
- the `RegisteredClient` should be returned in a new `OAuth2ClientAuthenticationToken` if the authentication succeeds
- the `Filter` should save the `OAuth2ClientAuthenticationToken` in the `SecurityContext`
- javadoc `class` and `public` methods
- Unit tests

### Specification References

[2.3.  Client Authentication](https://tools.ietf.org/html/rfc6749#section-2.3)
[3.1.  Token Endpoint](https://tools.ietf.org/html/rfc6749#section-3.2)
[4.1.  Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1)
[4.1.3.  Access Token Request](https://tools.ietf.org/html/rfc6749#section-4.1.3)

**Comment by pkostrzewa** [comment]
Can I work on this one?

**Comment by jgrandja** [comment]
Thank you @pkostrzewa. The issue is yours.

**Comment by paurav-munshi** [comment]
@jgrandja 

Does this relates to #5 ? If that is the case I have added a PR for that. Its still in progress but the code / design pattern from that PR can be used.

**Comment by jgrandja** [comment]
@paurav-munshi Please see my [comment](https://github.com/spring-projects-experimental/spring-authorization-server/pull/63#pullrequestreview-400812759)

**Comment by pkostrzewa** [comment]
I have basic implementation. Should I still work on it or leave this in favor of #64?

**Comment by jgrandja** [comment]
@pkostrzewa 

> I have basic implementation. Should I still work on it or leave this in favor of #64?

Please continue. The goal of #64 was to flush out the design for the `client_credentials` flow sample. This issue will address the `authorization_code` flow, and eventually be used for the `client_credentials` when we get to that feature at a later point.
