### ISSUE TITLE
Add Resource Server Sample

### ISSUE THREAD

**Issue by jzheaux** [spring-projects-experimental/spring-authorization-server#4]
Related to

It would be good to have a Resource Server sample that integrates with the authorization server sample. It should be quite similar to [the Resource Server sample](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2resourceserver/src) in Spring Security.

Like other samples, it should go into the `samples` directory. For simplicity, classes ought to be placed into a package called `sample`.

Given a valid token from the authorization server, the following test should pass:

```java
this.mockMvc.perform(get("/")
        .header("Authorization", "Bearer " + token))
        .andExpect(status().isOk());
```

**Comment by ketola** [comment]
Hi @jzheaux, can I start working on this? I think this should be pretty straight-forward as there's the example from the spring-security project.

**Comment by dfcoffin** [comment]
@jzheaux Please provide an explanation of what an integrated Resource Server sample would be?  Is it a separate project that accesses the Authorization Server or is it part of the Authorization project?  If a separate project does it share a common database with the Authorization Server like the spring-security-oauth project or does it use an Authorization Server interface?

**Comment by ketola** [comment]
As I understand this, the resource server example will now be the base for an example integration, and as described in the first comment, it's should validate the token. 
I don't think it needs to do much more now. The example should evolve when the actual auth server begins to have more features and then demonstrate those features.

**Comment by rwinch** [comment]
@ketola Thanks for reaching out! The issue is yours!
