### ISSUE TITLE
Implement Client Registration Model / Repository

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#40]
An authorization server must provide a mechanism(s) for registering Clients.

The initial implementation should provide an in-memory implementation of `RegisteredClientRepository`, similar to `InMemoryClientRegistrationRepository` in the `spring-security-oauth2-client` module.

### Implementation Requirements

- `InMemoryRegisteredClientRepository` should store in a `Map`
- `RegisteredClient` should provide a `Builder`, similar to `ClientRegistration`
- `RegisteredClient` should be immutable
- javadoc `class` and `public` methods
- Unit tests

### Specification References

[2. Client Registration](https://tools.ietf.org/html/rfc6749#section-2)

**Comment by anoopgarlapati** [comment]
@jgrandja I would like to start work on this issue. 
I want to understand if these classes should initially be in samples package or should I create a specific package for client registration similar to `spring-security-oauth2-client` module.

**Comment by jgrandja** [comment]
Thank you @anoopgarlapati. The issue is yours. See #65
