### ISSUE TITLE
Add Authorization (User) Consent page

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#42]

**Comment by paurav-munshi** [comment]
@jgrandja 

Is this related to the resource owner consent in authorization code grant flow ? If so, why is this on hold. Shouln't it be available for contribution ?

**Comment by anoopgarlapati** [comment]
@paurav-munshi Please check the project roadmap in ZenHub. Authorization consent epic is planned to be available for contribution in the upcoming week.

**Comment by paurav-munshi** [comment]
@anoopgarlapati I think I missed it in the road map when I was looking at it. Thanks for clarifying.

**Comment by jgrandja** [comment]
Thank you for pointing that out @anoopgarlapati.

@paurav-munshi 

> Is this related to the resource owner consent in authorization code grant flow ?

Yes it is. However, it's not needed at the moment to realize the full `authorization_code` grant flow.  My intention is to auto-approve the requested scopes for the initial iteration and then bring in the consent page afterwards.
