### ISSUE TITLE
Add a Client Credentials Authentication Filter

### ISSUE THREAD

**Issue by rwinch** [spring-projects-experimental/spring-authorization-server#5]
When the token endpoint from gh-3 is invoked, we will need to validate client credentials (we can add other grant types later). For this issue, we can use a hard coded client credentials. The idea is to keep this as simple as possible. We should validate every aspect of the client credentials grant type.

We should produce tests that verify the behaviour

**Comment by paurav-munshi** [comment]
@rwinch @jgrandja If no one is working on this, I can start working on it.

**Comment by rwinch** [comment]
Thanks for volunteering @paurav-munshi! The issue is yours

**Comment by tomvandenberge** [comment]
@paurav-munshi I have been working on this issue, too, and missed your message. I've created a filter and tests. Please let me know if you want me to create a pull request; I don't want to hijack your issue ;-)

**Comment by paurav-munshi** [comment]
I have been working on this but not completed it. If you think you are done, please create a PR. That should be fine.

**Comment by paurav-munshi** [comment]
@rwinch @jgrandja 

I have created a draft pull request for this issue. I would request you to review this PR and let me know if I am putting the correct thought process and also provide your inputs around it. Please note that this is still a work in progress. I have yet to write the test cases.

The idea is that to create a OAuth related templated filter which could be instantiated by composing various pieces in a configuration. So the same class can be instantiated for Client Credentials as well as authorization_code grant type, by providing different composable compoenents.

@tomvandenberge Feel free to share your work too especially if its on different line of thought.
