### ISSUE TITLE
Add support for Client Credentials Grant

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#51]
Add support for [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4).

**Comment by aDelNogal** [comment]
Are you planning to add JWT authentication? [rfc7523](https://tools.ietf.org/html/rfc7523#section-2.2)

**Comment by jgrandja** [comment]
@aDelNogal Yes. See the [roadmap](https://app.zenhub.com/workspaces/authorization-server-5e8f3182b5e8f5841bfc4902/roadmap) for planned features.
