### ISSUE TITLE
Add Spring Security

### ISSUE THREAD

**Issue by rwinch** [spring-projects-experimental/spring-authorization-server#6]
This task will add Spring Security and ensure that all of the additional `Filter`'s (gh-3, gh-5) are added to Spring Security in the proper places. We should start by using the existing Spring Security DSL (no need to create a custom DSL at this point).

**Comment by pkostrzewa** [comment]
Once required filters from gh-3 and gh-5 will be finished can I take a look at this?

**Comment by jgrandja** [comment]
Thanks @pkostrzewa. The issue is yours.

**Comment by pkostrzewa** [comment]
As gh-3 and gh-5 were closed I can progress with this issue. 

@jgrandja Could you please provide a detailed description with requirements? Similar to the one available for gh-5.

**Comment by jgrandja** [comment]
@pkostrzewa This issue would simply modify the `SecurityConfig` in the [minimal sample](https://github.com/spring-projects-experimental/spring-authorization-server/tree/master/samples/boot/minimal) by `http.addFilterAfter()` (or `http.addFilterBefore()` the `ClientCredentialsAuthenticationFilter` (in sample) and `OAuth2TokenEndpointFilter` (in `core`).

In addition, a test should demonstrate the client obtaining the access token via the `client_credentials` grant.

**Comment by jgrandja** [comment]
This is no longer needed as a result of gh-25 and commit 5927475
