### ISSUE TITLE
Stateful token/grant store

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects-experimental/spring-authorization-server#74]
Allows building an interface to allow a resource owner to:
 - View all clients with access to their resources
 - View all active third-party logins (technically the same thing)
 - View all scopes granted to each client
 - Revoke any and all of the above

In spring-security-oauth this was achieved by adding a findByUser method to a non-stateful TokenStore. There was also a separate granted scope store mechanism, but I never used a non-token mechanism.

N.B. the feature request template is the same as the bug report template

**Comment by jgrandja** [comment]
@OrangeDog The `OAuth2AuthorizationService` #43 is somewhat the equivalent of `TokenStore` but it has more capabilities then just storing the access token and optional refresh token. The initial design supports storing authorization `code`, granted `scope`(s) to the client by resource owner, etc. 

This design may change as we build it out but please follow this development and report any issues that it does not support to fulfill your use case(s). It's very early so operations will be added as we progress.

I'll close this as a duplicate.
