### ISSUE TITLE
well  authorization is comming

### ISSUE THREAD

**Issue by yuanjinzhong** [spring-projects-experimental/spring-authorization-server#75]
hello

can you check out a branch  build with maven ?

a lot of people  did not familiar with gradle 。

such as me , i am   familiar with maven.

**Comment by pkostrzewa** [comment]
Gradle is used as the build tool among other Spring projects so I don't think that would be possible.

**Comment by jgrandja** [comment]
@yuanjinzhong The [main page](https://github.com/spring-projects-experimental/spring-authorization-server) provides links on how to [build from source](https://github.com/spring-projects-experimental/spring-authorization-server#building-from-source) using Gradle. This project does not use Maven.

Also, questions should be asked on Stackoverflow, as we use GitHub issues for logging bug reports and feature enhancements.
