### ISSUE TITLE
Setup GitHub issue templates and configure chooser

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#8]
We need to setup GitHub issue / pull request templates.

We can leverage the existing [Spring Security templates](https://github.com/spring-projects/spring-security/tree/master/.github) as a base and modify if necessary.

It would also be very convenient to configure a template chooser so a user can select the type of issue being logged. See the Gradle ["New Issue Chooser"](https://github.com/gradle/gradle/issues/new/choose) as an example.

- [Configuring issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
- [Configuring the template chooser](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

**Comment by rwinch** [comment]
@jgrandja I have put this together. Please review and make changes as you see fit. If you are happy, please feel free to close this issue https://github.com/spring-projects-experimental/spring-authorization-server/issues/new/choose
