### ISSUE TITLE
Make RegisteredClient an interface

### ISSUE THREAD

**Issue by NickUfer** [spring-projects-experimental/spring-authorization-server#80]
**Context**
Hi,
I just wanted to throw in the idea of making the RegisteredClient an interface and move the current implementation to a default implementation. This way you could simply create an implementation of a JPA entity (with the needed annotations) to persist or retrieve it. I think the foundation for that was already laid with the RegisteredClientRepository interface.

**Comment by jgrandja** [comment]
@NickUfer Thanks for the feedback.

Interfaces allow for multiple implementations but `RegisteredClient` is not intended to have multiple implementations. However, you'll notice that `RegisteredClient` has a `protected` constructor as well as the `Builder`, allowing for extension outside of the framework. At this point, I don't see more than one implementation of `RegisteredClient` within the framework.

Furthermore, `RegisteredClient` is a domain-specific model and is not intended to serve as a one-to-one mapping to an entity model. I personally don't like to mix domain model with entity model. The underlying implementation that manages the `RegisteredClient` ( the `RegisteredClientRepository`) would be responsible for mapping the domain object to an entity object suitable for the datastore, eg. JPA, Redis (key-value store), etc.

Hope this makes sense?
