### ISSUE TITLE
Add JwtEncoder to support JWT/JWS

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#81]
The authorization server should support JSON Web Token (JWT) as an access token format, as well, it MUST be signed - JSON Web Signature (JWS).

`JwtEncoder` is the counterpart to `JwtDecoder` in the `spring-security-oauth2-jose` module.

### Implementation Requirements

- define `interface JwtEncoder`
- provide an implementation of `JwtEncoder` - `NimbusJwtEncoder` **NOTE:** The implementation should use the [Nimbus JOSE + JWT](https://connect2id.com/products/nimbus-jose-jwt) library 
- the `NimbusJwtEncoder` should have a `Builder`
- the `NimbusJwtEncoder` should support `HS256` (HMAC using SHA-256)
- the `NimbusJwtEncoder` should support `RS256` (RSASSA-PKCS1-v1_5 using SHA-256)
- the `NimbusJwtEncoder` should have a _"KeyManager"_ that provides the public/private/symmetric keys (also required by #82 )
- the `NimbusJwtEncoder` should be used by `OAuth2AuthorizationCodeAuthenticationProvider` #68 to produce a JWS
- javadoc `class` and `public` methods
- Unit tests

### Specification References
[JSON Web Token (JWT)](https://tools.ietf.org/html/rfc7519)
[JSON Web Signature (JWS)](https://tools.ietf.org/html/rfc7515)
[Cryptographic Algorithms for Digital Signatures and MACs](https://tools.ietf.org/html/rfc7518#section-3)

**Comment by idosal** [comment]
I'd love to be considered to take this when it's up for development.

**Comment by jgrandja** [comment]
Thank you for your interest @idosal. It looks like I have a team (internal to VMware) that will work on delivering the JOSE stack. If anything changes, I'll be sure to let you know.
