### ISSUE TITLE
Implement JWK Set Endpoint

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#82]
The authorization server should provide an endpoint that responds with the public key(s) used to verify the signature of a JWS. The public key(s) should be returned in the JWK Set format.

The `JwkSetEndpointFilter` should be implemented as a `Filter` similar to #31.

### Implementation Requirements

- the `Filter` should process `GET` requests for the (default) path `/oauth2/jwks`
- only public key(s) should be returned - private keys and symmetric keys must NOT be returned
- the `Filter` should have a _"KeyManager"_ that provides the public key(s) (also required by #81 )
- javadoc `class` and `public` methods
- Unit tests

### Specification References

[JSON Web Key (JWK)](https://tools.ietf.org/html/rfc7517)

**Comment by synek** [comment]
How exactly does this relate to #2? Should this replace the existing implementation in #31 or should it be a separate filter matching `/oauth/jwks` instead of `.well-known/jwk_uris`?

Perhaps @ovidiupopa91 is interested in this as he requested #2 originally :)

**Comment by ovidiupopa91** [comment]
Hi, yes, I'm interested in working on this issue.

**Comment by jgrandja** [comment]
@synek The goal of #2 was to flush out the implementation so it can be used in #4. It really was meant to be a simplified implementation compared to what is required here. Ultimately, #2 will be replaced by this implementation.

@ovidiupopa91 I have an internal team that will be delivering the implementations for the JOSE stack. I plan on logging a couple of new issues next week so take a look there to see if anything interests you.

**Comment by ovidiupopa91** [comment]
@jgrandja  ok, got it! I will take a look next week.
