### ISSUE TITLE
Implement Token Revocation Endpoint

### ISSUE THREAD

**Issue by jgrandja** [spring-projects-experimental/spring-authorization-server#83]
An authorization server should provide an endpoint that allows revoking an access token or refresh token.

The `OAuth2TokenRevocationEndpointFilter` should be implemented as a `Filter`.

### Implementation Requirements

- the `Filter` should process `POST` requests for the (default) path `/oauth2/revoke`
- The client must be authenticated #39 before the Revocation Request can be accepted
- the implementation must support the revocation of access tokens and refresh tokens
- the `Filter` should use the `OAuth2AuthorizationService` to _invalidate_ the token
- javadoc `class` and `public` methods
- Unit tests

### Specification References

[OAuth 2.0 Token Revocation](https://tools.ietf.org/html/rfc7009)

**Comment by synek** [comment]
I like to have a go at this one @jgrandja if that's possible.

**Comment by jgrandja** [comment]
Thanks for your interest @synek. This has already been assigned to an internal team member. Please keep an eye out for other issues coming up.
