### ISSUE TITLE
vscode build error

### ISSUE THREAD

**Issue by fujinjun** [spring-projects-experimental/spring-authorization-server#90]
config:
One or more cycles were detected in the build path of project 'spring-authorization-server-config'. The paths towards the cycle and cycle are:
->{spring-authorization-server-config, spring-authorization-server-core}
core:
One or more cycles were detected in the build path of project 'spring-authorization-server-core'. The paths towards the cycle and cycle are:
->{spring-authorization-server-config, spring-authorization-server-core}
minimal:
One or more cycles were detected in the build path of project 'spring-authorization-server-samples-boot-minimal'. The paths towards the cycle and cycle are:
spring-authorization-server-samples-boot-minimal->{spring-authorization-server-config, spring-authorization-server-core}

seems that caused by
 `	testCompile project(path: ':spring-authorization-server-config', configuration: 'tests')
`
in core/spring-authorization-server-core.gradle,
but gradle build is ok

**Comment by vasilaio** [comment]
same with eclipse 2020-03

**Comment by rcbandit111** [comment]
Hello guys! I'm interested to ask you is there any ETA for version 1.0? I would like to test this project.

**Comment by jgrandja** [comment]
Thanks for the report @fujinjun.

I haven't had any issues with Intellij.

However, I just pushed some changes in #95 that I believe will resolve your issue.
Can you please try with the latest master and let me know.

**Comment by vasilaio** [comment]
With eclipse 2020-06, this issue is fixed.

**Comment by jgrandja** [comment]
@fujinjun I haven't heard back from you so I'm going to assume it's working now given that @vasilaio has confirmed the issue has been resolved.

**Comment by fujinjun** [comment]
@jgrandja  yes,working now. thank you !
