### ISSUE TITLE
Add support for Resource Owner Password Credentials Grant 

### ISSUE THREAD

**Issue by Cepr0** [spring-projects-experimental/spring-authorization-server#94]
Hello, everyone )
I haven't found such an issue yet... 
Is there [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-1.3.3) implementation in plans?..

**Comment by jgrandja** [comment]
@Cepr0 We will not be providing support for the `password` grant as it's deprecated in OAuth 2.1. Please see this [post](https://aaronparecki.com/2019/12/12/21/its-time-for-oauth-2-dot-1) for further details.
